/**
 * Every piece of player-facing text, in English (plan P8). Keys are flat and
 * dotted; `{name}` marks a value filled in by `t`. Text shown only with the dev
 * tools on (the Wave Lab, readouts, telemetry) stays where it is.
 */
export const EN = {
  'app.name': 'Breakline',
  'app.tagline': 'Surf simulator',
  'menu.title': 'Main menu',
  'menu.surf': 'Surf',
  'menu.waveLab': 'Wave Lab',
  'menu.multiplayer': 'Multiplayer',
  'menu.comingSoon': 'Coming soon',
  'menu.logbook': 'Logbook',
  'menu.settings': 'Settings',
  'menu.fullscreen': 'Fullscreen',
  'menu.exitFullscreen': 'Exit fullscreen',
  'menu.version': 'v{version}',
  'menu.steamConnect': 'Connect Steam Controller',
  'menu.steamUnsupported': 'Steam Controller needs Chrome or Arc',
  'loading.break': 'Setting the break…',
  'loading.paddleOut': 'Paddling out…',
  'loading.lab': 'Filling the tank…',
  'lab.title': 'Wave Lab',
  'lab.settings': 'Settings',
  'lab.follow': 'Follow',
  'lab.pauseSea': 'Pause',
  'lab.playSea': 'Play',
  'lab.step': 'Step',
  'lab.slowMotion': 'Speed',
  'lab.hideUi': 'Hide',
  'lab.showUi': 'Show',
  'lab.menu': 'Menu',
  'lab.apply': 'Apply',
  'lab.newSea': 'New sea',
  'lab.pending': 'Changes waiting — Apply to rebuild the sea',
  'lab.group.break': 'Break',
  'lab.group.swell': 'Swell',
  'lab.group.conditions': 'Conditions',
  'lab.group.light': 'Light',
  'lab.group.water': 'Water',
  'lab.group.dev': 'Developer',
  'lab.source.buoy': 'Buoy',
  'lab.source.storm': 'Storm',
  'lab.source.practice': 'Practice',
  'lab.practiceNote': 'A steady {height} groundswell every {period} s, from {direction}°.',
  'lab.height': 'Height',
  'lab.period': 'Period',
  'lab.spread': 'Spread',
  'lab.spread.groundswell': 'Groundswell',
  'lab.spread.mixed': 'Mixed',
  'lab.spread.windswell': 'Windswell',
  'lab.stormWind': 'Storm wind',
  'lab.fetch': 'Fetch',
  'lab.duration': 'Duration',
  'lab.distance': 'Distance',
  'lab.stormArrives': 'Arrives at the spot as {height}, {period} s',
  'lab.direction': 'Direction',
  'lab.tide': 'Tide',
  'lab.wind': 'Local wind',
  'lab.wind.calm': 'Calm',
  'lab.wind.offshore': '{speed} offshore',
  'lab.wind.onshore': '{speed} onshore',
  'lab.sunHeight': 'Sun height',
  'lab.sunDirection': 'Sun direction',
  'lab.look.classic': 'Classic',
  'lab.look.rich': 'Rich',
  'lab.info': 'This wave',
  'lab.info.face': 'Face',
  'lab.info.period': 'Period',
  'lab.info.breaker': 'Breaking',
  'lab.info.peel': 'Peel',
  'lab.info.breaking': 'Surf zone breaking',
  'lab.info.nextSet': 'Next set',
  'lab.info.noFace': 'Flat here',
  'lab.info.waiting': 'Waiting for a break',
  'lab.info.setIn': 'in {seconds} s',
  'lab.info.setNow': 'arriving now',
  'lab.info.steady': 'steady swell',
  'lab.breaker.spilling': 'Spilling',
  'lab.breaker.plunging': 'Plunging',
  'lab.breaker.surging': 'Surging',
  'lab.breaker.none': 'Not breaking',
  'lab.peel.left': 'a left at {angle}°',
  'lab.peel.right': 'a right at {angle}°',
  'lab.peel.closeout': 'closes out',
  'lab.peel.mixed': 'mixed peaks',
  'lab.skill.beginner': 'easy to surf',
  'lab.skill.intermediate': 'good for surfing',
  'lab.skill.advanced': 'fast, for good surfers',
  'lab.skill.professional': 'very fast, experts only',
  'lab.hint': 'WASD move · drag look · Q/E down/up · F follow · 1–4 views · Space pause · H hide',
  'lab.jump.1': 'Overview',
  'lab.jump.2': 'Profile',
  'lab.jump.3': 'Below',
  'lab.jump.4': 'Cinematic',
  'lab.up': 'Up',
  'lab.down': 'Down',
  'surf.title': 'Pick a break',
  'surf.paddleOut': 'Paddle out',
  'surf.back': 'Back',
  'surfer.title': 'Your surfer',
  'surfer.preview': 'Your surfer on their board',
  'surfer.row.sex': 'Surfer',
  'surfer.row.look': 'Look',
  'surfer.row.outfit': 'Outfit',
  'surfer.row.color': 'Colour',
  'surfer.row.board': 'Board',
  'surfer.sex.female': 'Woman',
  'surfer.sex.male': 'Man',
  'surfer.look.1': '1',
  'surfer.look.2': '2',
  'surfer.outfit.fullsuit': 'Full suit',
  'surfer.outfit.springsuit': 'Spring suit',
  'surfer.outfit.vestBikini': 'Vest and bikini',
  'surfer.outfit.vestShorts': 'Vest and boardshorts',
  'surfer.color.teal': 'Teal',
  'surfer.color.coral': 'Coral',
  'surfer.color.sand': 'Sand',
  'surfer.color.navy': 'Navy',
  'surfer.color.lime': 'Lime',
  'surfer.color.graphite': 'Graphite',
  'surfer.board.classic': 'Classic',
  'surfer.board.sunset-fade': 'Sunset fade',
  'surfer.board.sea-glass': 'Sea glass',
  'surfer.board.midnight': 'Midnight',
  'surfer.board.coral-rail': 'Coral rail',
  'spot.beach': 'Beach',
  'spot.beach.blurb': 'Sandbar peaks and rips',
  'spot.point': 'Point',
  'spot.point.blurb': 'Long lines along a headland',
  'spot.reef': 'Reef',
  'spot.reef.blurb': 'Heavy left slab over shallow coral',
  'spot.canyon': 'Canyon',
  'spot.canyon.blurb': 'Waves focused by a deep channel',
  'cond.swell': 'Swell',
  'cond.swell.practice': 'Practice',
  'cond.swell.small': 'Small',
  'cond.swell.medium': 'Medium',
  'cond.swell.big': 'Big',
  'cond.tide': 'Tide',
  'cond.tide.low': 'Low',
  'cond.tide.mid': 'Mid',
  'cond.tide.high': 'High',
  'cond.wind': 'Wind',
  'cond.wind.offshore': 'Offshore',
  'cond.wind.calm': 'Calm',
  'cond.wind.onshore': 'Onshore',
  'cond.time': 'Time of day',
  'cond.time.dawn': 'Dawn',
  'cond.time.midday': 'Midday',
  'cond.time.sunset': 'Sunset',
  'hud.prompt.paddle': 'Hold {paddle} to paddle into a wave',
  'hud.prompt.popUp': 'Pop up now — {popUp}',
  'hud.prompt.rising': 'Getting up…',
  'hud.prompt.fallen': 'Wiped out — swim back and press {popUp} by the board, or {retry} to paddle out',
  'hud.pause': 'Pause',
  'hud.speed': 'Speed',
  'hud.balance': 'Balance',
  'hud.hint.paddle': 'Paddle',
  'hud.hint.popUp': 'Pop up',
  'hud.hint.steer': 'Steer',
  'hud.hint.pause': 'Pause',
  'hud.stick': 'Left stick',
  'hud.rightStick': 'Right stick',
  'hud.rotate': 'Turn your phone sideways for the best view',
  'touch.paddle': 'Paddle',
  'touch.retry': 'Replay',
  'touch.popUp': 'Pop up',
  'touch.crouch': 'Crouch',
  'touch.left': 'Steer left',
  'touch.right': 'Steer right',
  'pause.title': 'Paused',
  'pause.resume': 'Resume',
  'pause.replay': 'Replay wave',
  'pause.newWave': 'New wave',
  'pause.camera': 'Camera: {view}',
  'pause.settings': 'Settings',
  'pause.quit': 'Quit to menu',
  'view.front': 'Front',
  'view.behind': 'Behind',
  'view.side': 'Side',
  'view.overview': 'Overview',
  'view.cinematic': 'Cinematic',
  'view.profile': 'Profile',
  'view.below': 'Below',
  'end.wipeout': 'Wipeout',
  'end.complete': 'Ride complete',
  'end.ended': 'Ride over',
  'end.distance': 'Distance',
  'end.topSpeed': 'Top speed',
  'end.time': 'Ride time',
  'end.newBest': 'New best',
  'end.pocket': 'In the pocket',
  'end.turns': 'Turns (speed kept)',
  'end.score': 'Score',
  'end.bestTwo': 'Best two',
  'end.slowMotion': 'Slow motion ×{scale}',
  'maneuver.bottomTurn': 'Bottom turn',
  'maneuver.topTurn': 'Top turn',
  'maneuver.snap': 'Snap',
  'maneuver.cutback': 'Cutback',
  'end.replay': 'Replay ({key})',
  'end.newWave': 'New wave',
  'end.changeSpot': 'Change spot',
  'end.menu': 'Menu',
  'log.title': 'Logbook',
  'log.bests': 'Bests',
  'log.recent': 'Recent rides',
  'log.empty': 'No rides yet — paddle out from Surf.',
  'log.justNow': 'just now',
  'log.minutesAgo': '{n} min ago',
  'log.hoursAgo': '{n} h ago',
  'settings.title': 'Settings',
  'settings.gameplay': 'Gameplay',
  'settings.graphics': 'Graphics',
  'settings.controls': 'Controls',
  'settings.accessibility': 'Accessibility',
  'settings.audio': 'Audio',
  'settings.master': 'Master',
  'settings.sea': 'Sea',
  'settings.boardRider': 'Board and rider',
  'settings.interface': 'Interface',
  'settings.muteInBackground': 'Mute when out of view',
  'settings.monoAudio': 'Mono audio',
  'menu.sound': 'Sound on',
  'menu.muted': 'Sound off',
  'settings.reset': 'Reset',
  'settings.back': 'Back',
  'settings.nextWave': 'Next wave',
  'settings.pressKey': 'Press a key…',
  'settings.pressButton': 'Press a button…',
  'settings.cantBind': 'That one is reserved',
  'settings.on': 'On',
  'settings.off': 'Off',
  'settings.units': 'Units',
  'settings.units.metric': 'Metric',
  'settings.units.imperial': 'Imperial',
  'settings.defaultCamera': 'Default camera',
  'settings.touchControls': 'Touch controls',
  'settings.touch.auto': 'Auto',
  'settings.touch.on': 'On',
  'settings.touch.off': 'Off',
  'settings.showTelemetry': 'Show telemetry',
  'settings.preset': 'Quality',
  'settings.preset.auto': 'Auto ({preset})',
  'settings.preset.autoPending': 'Auto',
  'settings.preset.low': 'Low',
  'settings.preset.medium': 'Medium',
  'settings.preset.high': 'High',
  'settings.preset.ultra': 'Ultra',
  'settings.preset.custom': 'Custom',
  'settings.detection': 'Auto detection',
  'settings.redetect': 'Re-detect',
  'settings.detecting': 'Detecting…',
  'settings.advanced': 'Advanced',
  'settings.renderScale': 'Render scale',
  'settings.nativePixelDensity': 'Native pixel density',
  'settings.frameLimit': 'Frame limit',
  'settings.frameLimit.screen': 'Screen',
  'settings.frameLimit.60': '60 fps',
  'settings.frameLimit.30': '30 fps',
  'settings.waterSimulation': 'Water simulation',
  'settings.water.auto': 'Auto',
  'settings.water.fast': 'Fast',
  'settings.water.accurate': 'Accurate',
  'settings.seaDetail': 'Sea detail',
  'settings.sea.standard': 'Standard',
  'settings.sea.rich': 'Rich',
  'settings.waterLook': 'Water look',
  'settings.waterLook.classic': 'Classic',
  'settings.waterLook.rich': 'Rich',
  'settings.caustics': 'Caustics',
  'settings.sprayMist': 'Spray and mist',
  'settings.oceanView': 'Ocean view',
  'settings.ocean.near': 'Near',
  'settings.ocean.far': 'Far',
  'settings.foam': 'Foam',
  'settings.foam.simple': 'Simple',
  'settings.foam.detailed': 'Detailed',
  'settings.keyboard': 'Keyboard',
  'settings.gamepad': 'Gamepad',
  'settings.handedness': 'Touch layout',
  'settings.scoreRides': 'Score rides',
  'settings.balanceMeter': 'Balance meter',
  'settings.balanceMeter.practice': 'Practice',
  'settings.balanceMeter.always': 'Always',
  'settings.balanceMeter.never': 'Never',
  'settings.pocketReflex': 'Stay near the curl',
  'settings.pocketReflex.practice': 'Practice',
  'settings.pocketReflex.always': 'Always',
  'settings.pocketReflex.never': 'Never',
  'settings.hand.right': 'Right-handed',
  'settings.hand.left': 'Left-handed',
  'settings.steam': 'Steam Controller',
  'settings.steam.connection': 'Connection',
  'settings.steam.connect': 'Connect',
  'settings.steam.connected': 'Connected',
  'settings.steam.unsupported': 'Needs Chrome or Arc',
  'settings.steam.help': 'Chrome asks once. If the stick still moves the mouse, quit Steam.',
  'settings.sticks': 'Sticks',
  'settings.buttons': 'Buttons',
  'settings.trimStick': 'Trim stick',
  'settings.trimStick.right': 'Right stick',
  'settings.trimStick.left': 'Left stick',
  'settings.stickResponse': 'Stick response',
  'settings.stickResponse.help': 'Precise: finer near centre, full lock at the edge',
  'settings.stickResponse.linear': 'Linear',
  'settings.stickResponse.precise': 'Precise',
  'settings.deadzoneSteam': 'Steam Controller dead zone',
  'settings.deadzoneGamepad': 'Gamepad dead zone',
  'settings.deadzone.help': 'How far the stick moves before it counts',
  'settings.reducedMotion': 'Reduced motion',
  'settings.uiScale': 'UI scale',
  'settings.highContrastHud': 'High-contrast HUD',
  'action.paddle': 'Paddle',
  'action.popUp': 'Pop up / lie down',
  'action.steerLeft': 'Steer left',
  'action.steerRight': 'Steer right',
  'action.trimForward': 'Trim forward',
  'action.trimBack': 'Trim back',
  'action.crouch': 'Crouch',
  'action.hand': 'Hand in the face',
  'action.trimForward.help': 'Standing: weight forward, to run down the line',
  'action.trimBack.help': 'Standing: weight back, to slow down and stall',
  'action.crouch.help': 'Standing: get low; extend out of a turn to pump',
  'action.hand.help': 'Standing: drag the wave-side hand to slow in the pocket',
  'hint.lean': 'Lean with {keys} to carve',
  'hint.trim': '{keys} move your weight along the board',
  'hint.crouch': 'Hold {keys} to crouch',
  'hint.hand': 'Hold {keys} to drag a hand in the face',
  'action.retry': 'Paddle out again',
  'action.camera': 'Camera',
  'action.mute': 'Mute',
  'action.callLeft': 'Call "Left!"',
  'action.callRight': 'Call "Right!"',
  'action.callParty': 'Call "Party wave!"',
  'action.callNice': 'Call "Nice one!"',
  'notice.lowPerformance.title': 'Low performance detected',
  'notice.lowPerformance.body': 'Check that hardware acceleration is on in your browser settings, then restart the browser.',
  'notice.dismiss': 'Dismiss',
  'ride.reason.balance': 'Lost balance',
  'ride.reason.footSlip': 'Feet slipped',
  'ride.reason.lostBoard': 'Lost the board',
  'ride.reason.impact': 'Hit by the lip',
  'ride.reason.retry': 'Paddled back out',
  'ride.reason.outOfWave': 'Rode it out',
  'ride.reason.lostFace': 'The wave moved on',
  'ride.reason.inside': 'Reached the inside',
  'ride.reason.kickedOut': 'Kicked out',
  'ride.reason.waveDied': 'The wave died out',
  'ride.reason.lostWave': 'Lost the wave',
  'school.miss.time': "Time's up",
  'menu.school': 'Surf School',
  'menu.startHere': 'Start here',
  'loading.school': 'Waxing the board…',
  'school.title': 'Surf School',
  'school.lead': 'Learn one move at a time on the same good wave.',
  'school.progress': '{done} of {total} passed',
  'school.lesson': 'Lesson {n}',
  'school.freePractice': 'Free Practice',
  'school.freePractice.blurb': 'The same wave, no goals. Pick where you start.',
  'school.start.pocket': 'Standing in the pocket',
  'school.start.waiting': 'Prone, ready to catch',
  'school.go': 'Start',
  'school.next': 'Next lesson',
  'school.again': 'Again',
  'school.list': 'Lessons',
  'school.close': 'Close',
  'school.passed': 'Nice — lesson passed',
  'school.keys': 'Your controls',
  'school.restart': 'Restart',
  'school.explain': 'Show explanation',
  'school.slowMotion': 'Slow motion: {state}',
  'school.on': 'on',
  'school.off': 'off',
  'school.howTo': 'How to…',
  'school.missed': '{cause} — {tip}',
  'school.againSoon': 'Same wave again in a moment · {retry} now',
  'school.freeRide': 'Free Practice · {retry} to start again',
  'school.count': '{done} of {of}',
  'school.countSeconds': '{done} of {of} s',
  'school.loadError': "The lesson wave didn't load. Check your connection and try again.",
  'lesson.lean.title': 'Lean',
  'lesson.lean.blurb': 'Turn by putting the board on a rail',
  'lesson.lean.explain': 'A surfboard turns when you lean it onto one rail. Lean toward the wave to climb it and away to drop down. Keep the lean gentle and hold it for a moment: the rail needs time to bite before the board carves round.',
  'lesson.lean.tip': 'Hold the lean a little longer; the board needs a moment to bite.',
  'lesson.lean.prompt': 'Lean with {keys}, one way and then the other',
  'lesson.trim.title': 'Trim',
  'lesson.trim.blurb': 'Your weight sets your speed',
  'lesson.trim.explain': 'Where you stand on the board sets how fast it goes. Weight forward flattens the board and lets it run; weight back lifts the nose and slows it down. Surfers trim all the time to stay just ahead of the breaking part.',
  'lesson.trim.tip': 'Hold the weight shift for a full second and watch the speed change.',
  'lesson.trim.prompt': 'Weight forward to speed up, then back to slow down: {keys}',
  'lesson.crouch.title': 'Crouch and extend',
  'lesson.crouch.blurb': 'Pump for speed on the face',
  'lesson.crouch.explain': 'Bend your knees low as the board turns, then stand tall as it comes out of the turn. Done in rhythm on a curving line this pumps the board along, like a skateboarder in a bowl. On flat water it does nothing: the speed comes from the wave.',
  'lesson.crouch.tip': 'Crouch and stand in a steady rhythm, and keep the board moving along the face.',
  'lesson.crouch.prompt': 'Crouch and stand tall three times: {keys}',
  'lesson.bottomTurn.title': 'Bottom turn',
  'lesson.bottomTurn.blurb': 'Turn at the bottom and head back up',
  'lesson.bottomTurn.explain': 'Ride down the face, then crouch low and lean hard toward the wave to swing back up it. The bottom turn turns the speed from the drop into height on the face, and sets up everything that follows.',
  'lesson.bottomTurn.tip': 'Get low on the face first, then lean and crouch together.',
  'lesson.bottomTurn.prompt': 'Drop down the face, then lean back up and crouch: {keys}',
  'lesson.topTurn.title': 'Top turn',
  'lesson.topTurn.blurb': 'Turn near the lip and come back down',
  'lesson.topTurn.explain': 'Climb up the face toward the lip, then shift your weight back and lean away from the wave to turn back down. A quick, sharp one is a snap. It keeps you close to the breaking part instead of racing out onto the flat.',
  'lesson.topTurn.tip': 'Wait until you are high on the face before you turn back down.',
  'lesson.topTurn.prompt': 'Climb high, then turn back down: {keys}',
  'lesson.hand.title': 'Hand and stall',
  'lesson.hand.blurb': 'Drag a hand to slow down',
  'lesson.hand.explain': 'Reach down and drag your wave-side hand in the face. The drag slows the board, so the breaking part catches up with you. Surfers stall like this to stay in the steepest, most powerful spot, and to set up a barrel.',
  'lesson.hand.tip': 'Keep the hand in for a full second, and let the curl come to you.',
  'lesson.hand.prompt': 'Drag your hand with {keys} to let the curl catch up',
  'lesson.pocket.title': 'Stay in the pocket',
  'lesson.pocket.blurb': 'Ride the steepest part, by the curl',
  'lesson.pocket.explain': 'The pocket is high on the face, right beside the breaking part: the steepest, fastest water on the wave. Too far ahead and the wave loses you; too far back and it breaks on you. Trim and lean to hold your place just ahead of the curl.',
  'lesson.pocket.tip': 'Stay high on the face and slow down if you run ahead of the curl.',
  'lesson.pocket.prompt': 'Stay high by the breaking part with {keys}',
  'lesson.popUp.title': 'Pop up',
  'lesson.popUp.blurb': 'From lying down to standing',
  'lesson.popUp.explain': 'Once the wave is carrying the board, push up and jump to your feet in one move. Too early and the board is still slow; too late and it tips down the face. The board and the wave tell you when: pop up as soon as the prompt says now.',
  'lesson.popUp.tip': 'Pop up the moment the prompt says now, then keep still for two seconds.',
  'lesson.popUp.prompt': 'Pop up with {keys} when the wave carries you',
  'lesson.catch.title': 'Paddle and catch',
  'lesson.catch.blurb': 'Catch the wave from the lineup',
  'lesson.catch.explain': 'Lie on the board facing the beach and paddle as the wave rises behind you. You need to be moving when it arrives, or it passes under you. When you feel it carrying the board, pop up.',
  'lesson.catch.tip': 'Start paddling a little earlier, while the wave is still a few metres behind.',
  'lesson.catch.prompt': 'Paddle with {keys} as the wave comes, then pop up',
  // Online (N1).
  'online.title': 'Multiplayer',
  'online.lead': 'Surf with friends: make a room and share its link, or join one.',
  'online.name': 'Your name',
  'online.namePlaceholder': 'How others see you',
  'online.createTitle': 'Make a room',
  'online.create': 'Create room',
  'online.joinTitle': 'Join a room',
  'online.code': 'Room code',
  'online.codePlaceholder': 'e.g. K7PX-3MQA',
  'online.join': 'Join',
  'online.cap': 'Players',
  'online.checkingGpu': 'Checking this browser…',
  'online.joining': 'Joining the lineup…',
  'online.handover': 'Taking the sea from the lineup…',
  'online.catchingUp': 'Catching up with the sea…',
  'online.catchingUpBy': 'Catching up with the sea… {s} s to go',
  'online.resyncing': 'Catching up with the sea…',
  'online.noWebGpu': "This browser can't run the shared sea. Use a current Chrome or Safari.",
  'online.refused.full': 'This room is full.',
  'online.refused.version': 'A new version is out — reload.',
  'online.refused.notFound': "This room has closed or doesn't exist.",
  'online.refused.kicked': 'You were removed from this room.',
  'online.refused.invalid': "That didn't work. Check your name and try again.",
  'online.unreachable': "Couldn't reach the room server.",
  'online.reconnecting': 'Reconnecting…',
  'online.leave': 'Leave room',
  'online.players': 'Players',
  'online.you': 'you',
  'online.kick': 'Kick',
  'online.copyLink': 'Copy link',
  'online.copied': 'Link copied',
  'online.roomCode': 'Room {code}',
  'online.respawnIn': 'Back in the lineup in {s} s',
  'online.feed': '{name} · {distance} · {seconds} s',
  'online.call.left': 'Left!',
  'online.call.right': 'Right!',
  'online.call.party': 'Party wave!',
  'online.call.nice': 'Nice one!',
  'settings.nameTags': 'Name tags',
  'log.online': 'Online',
  'settings.nameTags.hint': 'Names over the other surfers online',
} as const;

export type StringKey = keyof typeof EN;

/** The text for `key`, with each `{name}` replaced from `vars`; a missing value is a bug and throws. */
export function t(key: StringKey, vars: Record<string, string | number> = {}): string {
  return EN[key].replace(/\{(\w+)\}/g, (_, name: string) => {
    if (!(name in vars)) throw new Error(`Missing value for {${name}} in "${key}"`);
    return String(vars[name]);
  });
}
