/**
 * Every piece of player-facing text, in English (plan P8). Keys are flat and
 * dotted; `{name}` marks a value filled in by `t`. Text shown only with the dev
 * tools on (the Wave Lab, readouts, telemetry) stays where it is.
 */
export const EN = {
  'app.name': 'Breakline',
  'app.tagline': 'Surf simulator',
  'menu.title': 'Main menu',
  'menu.surf': 'Surf',
  'menu.waveLab': 'Wave Lab',
  'menu.multiplayer': 'Multiplayer',
  'menu.comingSoon': 'Coming soon',
  'menu.logbook': 'Logbook',
  'menu.settings': 'Settings',
  'menu.fullscreen': 'Fullscreen',
  'menu.exitFullscreen': 'Exit fullscreen',
  'menu.version': 'v{version}',
  'loading.break': 'Setting the break…',
  'loading.paddleOut': 'Paddling out…',
  'surf.title': 'Pick a break',
  'surf.paddleOut': 'Paddle out',
  'surf.back': 'Back',
  'spot.beach': 'Beach',
  'spot.beach.blurb': 'Sandbar peaks and rips',
  'spot.point': 'Point',
  'spot.point.blurb': 'Long lines along a headland',
  'spot.reef': 'Reef',
  'spot.reef.blurb': 'Steep shelf, fast and hollow',
  'spot.canyon': 'Canyon',
  'spot.canyon.blurb': 'Waves focused by a deep channel',
  'cond.swell': 'Swell',
  'cond.swell.practice': 'Practice',
  'cond.swell.small': 'Small',
  'cond.swell.medium': 'Medium',
  'cond.swell.big': 'Big',
  'cond.tide': 'Tide',
  'cond.tide.low': 'Low',
  'cond.tide.mid': 'Mid',
  'cond.tide.high': 'High',
  'cond.wind': 'Wind',
  'cond.wind.offshore': 'Offshore',
  'cond.wind.calm': 'Calm',
  'cond.wind.onshore': 'Onshore',
  'cond.time': 'Time of day',
  'cond.time.dawn': 'Dawn',
  'cond.time.midday': 'Midday',
  'cond.time.sunset': 'Sunset',
  'hud.prompt.paddle': 'Hold {paddle} to paddle into a wave',
  'hud.prompt.popUp': 'Pop up now — {popUp}',
  'hud.prompt.rising': 'Getting up…',
  'hud.prompt.fallen': 'Wiped out — swim back and press {popUp} by the board, or {retry} to paddle out',
  'hud.pause': 'Pause',
  'hud.speed': 'Speed',
  'hud.balance': 'Balance',
  'hud.hint.paddle': 'Paddle',
  'hud.hint.popUp': 'Pop up',
  'hud.hint.steer': 'Steer',
  'hud.hint.pause': 'Pause',
  'hud.stick': 'Left stick',
  'hud.rotate': 'Turn your phone sideways for the best view',
  'touch.paddle': 'Paddle',
  'touch.retry': 'Replay',
  'touch.popUp': 'Pop up',
  'touch.left': 'Steer left',
  'touch.right': 'Steer right',
  'pause.title': 'Paused',
  'pause.resume': 'Resume',
  'pause.replay': 'Replay wave',
  'pause.newWave': 'New wave',
  'pause.camera': 'Camera: {view}',
  'pause.settings': 'Settings',
  'pause.quit': 'Quit to menu',
  'view.front': 'Front',
  'view.behind': 'Behind',
  'view.side': 'Side',
  'view.overview': 'Overview',
  'view.cinematic': 'Cinematic',
  'view.profile': 'Profile',
  'view.below': 'Below',
  'end.wipeout': 'Wipeout',
  'end.complete': 'Ride complete',
  'end.ended': 'Ride over',
  'end.distance': 'Distance',
  'end.topSpeed': 'Top speed',
  'end.time': 'Ride time',
  'end.newBest': 'New best',
  'end.replay': 'Replay ({key})',
  'end.newWave': 'New wave',
  'end.changeSpot': 'Change spot',
  'end.menu': 'Menu',
  'log.title': 'Logbook',
  'log.bests': 'Bests',
  'log.recent': 'Recent rides',
  'log.empty': 'No rides yet — paddle out from Surf.',
  'log.justNow': 'just now',
  'log.minutesAgo': '{n} min ago',
  'log.hoursAgo': '{n} h ago',
  'settings.title': 'Settings',
  'settings.gameplay': 'Gameplay',
  'settings.graphics': 'Graphics',
  'settings.controls': 'Controls',
  'settings.accessibility': 'Accessibility',
  'settings.reset': 'Reset',
  'settings.back': 'Back',
  'settings.nextWave': 'Next wave',
  'settings.pressKey': 'Press a key…',
  'settings.pressButton': 'Press a button…',
  'settings.cantBind': 'That one is reserved',
  'settings.on': 'On',
  'settings.off': 'Off',
  'settings.units': 'Units',
  'settings.units.metric': 'Metric',
  'settings.units.imperial': 'Imperial',
  'settings.defaultCamera': 'Default camera',
  'settings.touchControls': 'Touch controls',
  'settings.touch.auto': 'Auto',
  'settings.touch.on': 'On',
  'settings.touch.off': 'Off',
  'settings.showTelemetry': 'Show telemetry',
  'settings.preset': 'Quality',
  'settings.preset.auto': 'Auto ({preset})',
  'settings.preset.autoPending': 'Auto',
  'settings.preset.low': 'Low',
  'settings.preset.medium': 'Medium',
  'settings.preset.high': 'High',
  'settings.preset.ultra': 'Ultra',
  'settings.preset.custom': 'Custom',
  'settings.detection': 'Auto detection',
  'settings.redetect': 'Re-detect',
  'settings.detecting': 'Detecting…',
  'settings.advanced': 'Advanced',
  'settings.renderScale': 'Render scale',
  'settings.nativePixelDensity': 'Native pixel density',
  'settings.frameLimit': 'Frame limit',
  'settings.frameLimit.screen': 'Screen',
  'settings.frameLimit.60': '60 fps',
  'settings.frameLimit.30': '30 fps',
  'settings.waterSimulation': 'Water simulation',
  'settings.water.auto': 'Auto',
  'settings.water.fast': 'Fast',
  'settings.water.accurate': 'Accurate',
  'settings.seaDetail': 'Sea detail',
  'settings.sea.standard': 'Standard',
  'settings.sea.rich': 'Rich',
  'settings.caustics': 'Caustics',
  'settings.sprayMist': 'Spray and mist',
  'settings.oceanView': 'Ocean view',
  'settings.ocean.near': 'Near',
  'settings.ocean.far': 'Far',
  'settings.foam': 'Foam',
  'settings.foam.simple': 'Simple',
  'settings.foam.detailed': 'Detailed',
  'settings.keyboard': 'Keyboard',
  'settings.gamepad': 'Gamepad',
  'settings.handedness': 'Touch layout',
  'settings.hand.right': 'Right-handed',
  'settings.hand.left': 'Left-handed',
  'settings.reducedMotion': 'Reduced motion',
  'settings.uiScale': 'UI scale',
  'settings.highContrastHud': 'High-contrast HUD',
  'action.paddle': 'Paddle',
  'action.popUp': 'Pop up',
  'action.steerLeft': 'Steer left',
  'action.steerRight': 'Steer right',
  'action.retry': 'Paddle out again',
  'action.camera': 'Camera',
  'notice.lowPerformance.title': 'Low performance detected',
  'notice.lowPerformance.body': 'Check that hardware acceleration is on in your browser settings, then restart the browser.',
  'notice.dismiss': 'Dismiss',
  'ride.reason.balance': 'Lost balance',
  'ride.reason.footSlip': 'Feet slipped',
  'ride.reason.lostBoard': 'Lost the board',
  'ride.reason.impact': 'Hit by the lip',
  'ride.reason.retry': 'Paddled back out',
  'ride.reason.outOfWave': 'Rode it out',
} as const;

export type StringKey = keyof typeof EN;

/** The text for `key`, with each `{name}` replaced from `vars`; a missing value is a bug and throws. */
export function t(key: StringKey, vars: Record<string, string | number> = {}): string {
  return EN[key].replace(/\{(\w+)\}/g, (_, name: string) => {
    if (!(name in vars)) throw new Error(`Missing value for {${name}} in "${key}"`);
    return String(vars[name]);
  });
}
