/**
 * Every piece of player-facing text, in English (plan P8). Keys are flat and
 * dotted; `{name}` marks a value filled in by `t`. Text shown only with the dev
 * tools on (the Wave Lab, readouts, telemetry) stays where it is.
 */
export const EN = {
  'app.name': 'Breakline',
  'app.tagline': 'Surf simulator',
  'menu.title': 'Main menu',
  'menu.surf': 'Surf',
  'menu.waveLab': 'Wave Lab',
  'menu.multiplayer': 'Multiplayer',
  'menu.comingSoon': 'Coming soon',
  'menu.logbook': 'Logbook',
  'menu.settings': 'Settings',
  'menu.fullscreen': 'Fullscreen',
  'menu.exitFullscreen': 'Exit fullscreen',
  'menu.version': 'v{version}',
  'loading.break': 'Setting the break…',
  'loading.paddleOut': 'Paddling out…',
  'surf.title': 'Pick a break',
  'surf.paddleOut': 'Paddle out',
  'surf.back': 'Back',
  'spot.beach': 'Beach',
  'spot.beach.blurb': 'Sandbar peaks and rips',
  'spot.point': 'Point',
  'spot.point.blurb': 'Long lines along a headland',
  'spot.reef': 'Reef',
  'spot.reef.blurb': 'Steep shelf, fast and hollow',
  'spot.canyon': 'Canyon',
  'spot.canyon.blurb': 'Waves focused by a deep channel',
  'cond.swell': 'Swell',
  'cond.swell.practice': 'Practice',
  'cond.swell.small': 'Small',
  'cond.swell.medium': 'Medium',
  'cond.swell.big': 'Big',
  'cond.tide': 'Tide',
  'cond.tide.low': 'Low',
  'cond.tide.mid': 'Mid',
  'cond.tide.high': 'High',
  'cond.wind': 'Wind',
  'cond.wind.offshore': 'Offshore',
  'cond.wind.calm': 'Calm',
  'cond.wind.onshore': 'Onshore',
  'cond.time': 'Time of day',
  'cond.time.dawn': 'Dawn',
  'cond.time.midday': 'Midday',
  'cond.time.sunset': 'Sunset',
  'hud.prompt.paddle': 'Hold {paddle} to paddle into a wave',
  'hud.prompt.popUp': 'Pop up now — {popUp}',
  'hud.prompt.rising': 'Getting up…',
  'hud.prompt.fallen': 'Wiped out — swim back and press {popUp} by the board, or {retry} to paddle out',
  'hud.pause': 'Pause',
  'hud.speed': 'Speed',
  'hud.balance': 'Balance',
  'hud.hint.paddle': 'Paddle',
  'hud.hint.popUp': 'Pop up',
  'hud.hint.steer': 'Steer',
  'hud.hint.pause': 'Pause',
  'hud.stick': 'Left stick',
  'touch.paddle': 'Hold to paddle',
  'touch.popUp': 'Pop up',
  'touch.left': 'Steer left',
  'touch.right': 'Steer right',
  'pause.title': 'Paused',
  'pause.resume': 'Resume',
  'pause.replay': 'Replay wave',
  'pause.newWave': 'New wave',
  'pause.camera': 'Camera: {view}',
  'pause.settings': 'Settings',
  'pause.quit': 'Quit to menu',
  'view.front': 'Front',
  'view.behind': 'Behind',
  'view.side': 'Side',
  'view.overview': 'Overview',
  'view.cinematic': 'Cinematic',
  'view.profile': 'Profile',
  'view.below': 'Below',
  'end.wipeout': 'Wipeout',
  'end.complete': 'Ride complete',
  'end.ended': 'Ride over',
  'end.distance': 'Distance',
  'end.topSpeed': 'Top speed',
  'end.time': 'Ride time',
  'end.newBest': 'New best',
  'end.replay': 'Replay ({key})',
  'end.newWave': 'New wave',
  'end.changeSpot': 'Change spot',
  'end.menu': 'Menu',
  'notice.lowPerformance.title': 'Low performance detected',
  'notice.lowPerformance.body': 'Check that hardware acceleration is on in your browser settings, then restart the browser.',
  'notice.dismiss': 'Dismiss',
  'ride.reason.balance': 'Lost balance',
  'ride.reason.footSlip': 'Feet slipped',
  'ride.reason.lostBoard': 'Lost the board',
  'ride.reason.impact': 'Hit by the lip',
  'ride.reason.retry': 'Paddled back out',
  'ride.reason.outOfWave': 'Rode it out',
} as const;

export type StringKey = keyof typeof EN;

/** The text for `key`, with each `{name}` replaced from `vars`; a missing value is a bug and throws. */
export function t(key: StringKey, vars: Record<string, string | number> = {}): string {
  return EN[key].replace(/\{(\w+)\}/g, (_, name: string) => {
    if (!(name in vars)) throw new Error(`Missing value for {${name}} in "${key}"`);
    return String(vars[name]);
  });
}
