// Writes docs/research/fps-report.md from the survey runs in docs/research/fps/*.json (dev only).
//   node scripts/browser/fps-report.mjs [docs/research/fps] [docs/research/fps-report.md]
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = process.argv[2] ?? 'docs/research/fps';
const OUT = process.argv[3] ?? 'docs/research/fps-report.md';
const runs = readdirSync(DIR).filter((f) => f.endsWith('.json')).sort()
  .map((file) => ({ file, ...JSON.parse(readFileSync(join(DIR, file), 'utf8')) }));

const PRESETS = ['Low', 'Medium', 'High', 'Ultra'];
const table = (head, rows, align) => [
  `| ${head.join(' | ')} |`,
  `|${head.map((_, i) => (align?.[i] === 'l' ? '---' : '---:')).join('|')}|`,
  ...rows.map((row) => `| ${row.join(' | ')} |`),
].join('\n');
/** The solver's tier and its step through the window (median, worst), ms. */
const solverShort = (r) => {
  const tier = /\b(GPU|CPU)\b/.exec(r.solver ?? '')?.[1];
  if (r.solverMsP50 !== undefined) return `${tier ?? ''} ${r.solverMsP50} (max ${r.solverMsMax})`.trim();
  const match = /([\d.]+) ms\/step/.exec(r.solver ?? '');
  return match ? `${tier ?? ''} ${match[1]}`.trim() : '—';
};
const ok = (r) => r.error === undefined;
const machineLine = (run) => `${run.machine.model} · ${run.machine.chip} · ${run.machine.memory}`;
/** Runs timed before `gpuTiming` added one GPU timer per WebGL context: the Surf screen, with the surfer preview's, read about twice. */
const doubled = (run, r) => !run.gpuTiming && r.screen.startsWith('Surf');
/** A row's GPU ms (median, then the 95th percentile), marked ‡ when counted twice, with the preview's own timer apart. */
const gpuText = (run, r, between) => (r.gpuMsP50 === undefined ? '—'
  : `${r.gpuMsP50}${between}${r.gpuMsP95}${between === ' (' ? ')' : ''}${doubled(run, r) ? ' ‡' : ''}${r.gpuOtherMsP50 !== undefined ? ` · preview ≤ ${r.gpuOtherMsP50}` : ''}`);
const DOUBLED_NOTE = '‡ Timed before the survey kept the game\'s context apart: it added one timer per WebGL context, so this screen, with the surfer preview\'s context, reads about twice its GPU time. The preview itself costs about 0.5 ms (the Low column, where the game draws a still frame).';

const lines = [
  '# Frame-rate report',
  '',
  `Generated by \`npm run report:fps\` from the survey runs in [fps/](fps/) (\`npm run survey:fps\`, then \`npm run survey:fps -- --features\`). Reported, not asserted.`,
  '',
  '**Method.** Google Chrome on a fresh profile drives the production build (`vite build` + `vite preview`) through every screen at each graphics preset. The window is sized so the page is the stated number of CSS pixels. Each screen settles (1.5 s for menus, 5 s after a ride loads), then every display frame is timed for the stated seconds.',
  '',
  '- **FPS** is frames over time.',
  '- **1 % low** is the frame rate at the 99th-percentile frame time.',
  '- **Main thread** is the time spent in the page\'s animation-frame callbacks: the game\'s simulation hand-off, scene updates and WebGL command submission. When the frame time is well above it, the GPU (or the compositor) is the limit.',
  '- **Draws** and **triangles** are the WebGL draw calls and triangles submitted per frame (median). The WebGPU water solver runs in a worker and is not counted.',
  '- **Solver** is the surf zone\'s worker step: its compute tier, and ms per step through the window (median, worst), read from the telemetry at 2 Hz. Stage 2 keeps real time at 15 ms or less (`STAGE2_REALTIME_MS`).',
  '- **GPU ms** is the GPU time of the game\'s WebGL commands each frame (`EXT_disjoint_timer_query_webgl2`, timed around the frame callbacks that issue them). The display caps the frame rate, so this is the headroom: at 120 Hz a frame has 8.3 ms, at 60 Hz 16.7 ms. It leaves out the compositor and the WebGPU solver, which share the GPU.',
  '- **What a GPU timer counts.** On ANGLE Metal a timer spans the GPU\'s timeline, so it also counts work that overlaps it: another context\'s on the same page, and other processes\'. Two things follow. The Surf screen\'s surfer preview (a second WebGL context) is shown apart as *preview ≤*, its own timer, which may include the game\'s overlapping work; the two are never added, and the game\'s reading may include the preview\'s. And a survey belongs on an otherwise idle machine: another GPU-heavy process inflates every reading. Compare readings on the same screen, before and after a change.',
  '',
  'The rider sits in the lineup without input during a ride sample. The menus draw a live surf zone behind them, at a spot the game picks (seeded, so each run sees the same one). Math.random is seeded so runs repeat. The display caps the frame rate at its refresh.',
  '',
];

// Every machine at a glance: rides averaged over the spots, per preset.
lines.push('## Machines', '');
lines.push(table(['Run', 'Machine', 'GPU', 'Display', 'Window', 'Frame cap', 'Low', 'Medium', 'High', 'Ultra'], runs.filter((run) => run.results.some((r) => PRESETS.includes(r.setting))).map((run) => {
  const ride = (preset) => {
    const rides = run.results.filter((r) => ok(r) && r.setting === preset && r.screen.startsWith('Ride'));
    return rides.length ? (rides.reduce((sum, r) => sum + r.fps, 0) / rides.length).toFixed(0) : '—';
  };
  return [`[${run.file.replace(/\.json$/, '')}](fps/${run.file})`, machineLine(run), `${run.machine.gpuCores}-core`, `${run.browser.refreshHz} Hz`, `${run.window} @${run.browser.devicePixelRatio}×`, run.frameCap ?? 'display refresh (vsync)', ...PRESETS.map(ride)];
}), ['l', 'l', 'l', 'l', 'l', 'l']));
lines.push('', 'Mean ride FPS over the four spots, per preset.', '');

for (const run of runs) {
  const m = run.machine;
  const b = run.browser;
  lines.push(`## ${run.file.replace(/\.json$/, '')}`, '');
  lines.push(table(['Hardware', ''], [
    ['Machine', `${m.model} (${m.modelId})`],
    ['Chip', `${m.chip}, ${m.cores}`],
    ['GPU', `${m.gpu}, ${m.gpuCores} cores, ${m.metal?.replace('spdisplays_', '').replace('metal', 'Metal ') ?? ''}`],
    ['Memory', m.memory],
    ['Display', m.displays.map((d) => `${d.name} ${d.resolution ?? d.pixels ?? ''}${d.main ? ' (main)' : ''}`).join('; ') + `; measured ${b.refreshHz} Hz`],
    ['OS', m.os],
    ['Browser', `${b.chrome} · WebGL: ${b.webgl} · WebGPU: ${b.webgpu}`],
    ['Page', `${b.viewport} CSS px at ${b.devicePixelRatio}× (screen ${b.screen})`],
    ['Frame cap', run.frameCap ?? 'display refresh (vsync)'],
    ['Power', (() => {
      const during = [...new Set(run.results.map((r) => r.power?.split(' ')[0]).filter(Boolean))];
      const through = during.length === 1 ? `, ${during[0]} throughout` : during.length > 1 ? `, changed during the run (${during.join(', ')}): see each row` : '';
      return `${m.power} at start${through}${m.lowPowerMode ? ', Low Power Mode on' : ''}`;
    })()],
    ['Load average at start', run.loadAverage.join(', ')],
    ['Build', `${run.build}${run.commit ? ` at \`${run.commit}\`` : ''}, ${run.date.slice(0, 16).replace('T', ' ')} UTC`],
  ], ['l', 'l']));
  lines.push('');

  const failures = run.results.filter((r) => !ok(r));
  const presetRows = run.results.filter((r) => ok(r) && PRESETS.includes(r.setting));
  if (presetRows.length) {
    const screens = [...new Set([...presetRows, ...failures.filter((r) => PRESETS.includes(r.setting))].map((r) => r.screen))];
    const cell = (screen, preset) => {
      const r = presetRows.find((x) => x.screen === screen && x.setting === preset);
      const failed = failures.some((x) => x.screen === screen && x.setting === preset);
      return r ? `${r.fps.toFixed(0)} (${r.fps1Low.toFixed(0)})` : failed ? 'failed' : '—';
    };
    const shown = PRESETS.filter((p) => presetRows.some((r) => r.setting === p));
    lines.push('### FPS by screen and preset', '', 'FPS, with the 1 % low in brackets.', '');
    lines.push(table(['Screen', ...shown], screens.map((screen) => [screen, ...shown.map((p) => cell(screen, p))]), ['l']));
    lines.push('');
    if (presetRows.some((r) => r.gpuMsP50 !== undefined)) {
      const gpuCell = (screen, preset) => {
        const r = presetRows.find((x) => x.screen === screen && x.setting === preset);
        return r ? gpuText(run, r, ' (') : '—';
      };
      lines.push('### GPU time per frame by screen and preset', '', `GPU ms per frame, median with the 95th percentile in brackets. The budget at ${run.browser.refreshHz} Hz is ${(1000 / run.browser.refreshHz).toFixed(1)} ms.`, '');
      lines.push(table(['Screen', ...shown], screens.map((screen) => [screen, ...shown.map((p) => gpuCell(screen, p))]), ['l']));
      lines.push('');
      if (presetRows.some((r) => doubled(run, r) && r.gpuMsP50 !== undefined)) lines.push(DOUBLED_NOTE, '');
    }
    for (const preset of PRESETS) {
      const rows = presetRows.filter((r) => r.setting === preset);
      if (!rows.length) continue;
      lines.push(`### ${preset}`, '');
      lines.push(table(['Screen', 'FPS', '1 % low', 'Frame p50 ms', 'p95 ms', 'p99 ms', 'Worst ms', 'GPU p50 / p95 ms', 'Main thread p50 / p95 ms', 'Draws', 'Triangles k', 'Canvas px', 'Solver ms', 'JS heap MB', 'Power'],
        rows.map((r) => [r.screen, r.fps.toFixed(1), r.fps1Low.toFixed(1), r.frameMsP50, r.frameMsP95, r.frameMsP99, r.frameMsMax, gpuText(run, r, ' / '), `${r.mainThreadMsP50} / ${r.mainThreadMsP95}`, r.drawCalls, r.trianglesK, r.canvas, solverShort(r), r.heapMB ?? '—', r.power ?? '—']), ['l']));
      lines.push('');
    }
  }

  const featureRows = run.results.filter((r) => ok(r) && !PRESETS.includes(r.setting));
  if (featureRows.length) {
    const base = featureRows.find((r) => r.setting === 'High (baseline)');
    lines.push(`### Settings one at a time (${featureRows[0].screen}, from High)`, '');
    lines.push('Each row changes one advanced setting from the High preset (the Custom preset; the surfer keeps its detail). Δ is against the High baseline in the same run: with the frame rate at the cap, the GPU time says what each setting costs.', '');
    const delta = (value, baseValue, digits = 1) => (value === undefined || baseValue === undefined ? '—' : `${value - baseValue >= 0 ? '+' : ''}${(value - baseValue).toFixed(digits)}`);
    lines.push(table(['Setting', 'FPS', 'Δ FPS', '1 % low', 'GPU p50 ms', 'Δ GPU ms', 'GPU p95 ms', 'Frame p95 ms', 'Main thread p50 ms', 'Draws', 'Triangles k', 'Canvas px', 'Solver ms', 'Power'],
      featureRows.map((r) => [r.remeasured ? `${r.setting} †` : r.setting, r.fps.toFixed(1), base && r !== base ? delta(r.fps, base.fps) : '—', r.fps1Low.toFixed(1), r.gpuMsP50 ?? '—', base && r !== base ? delta(r.gpuMsP50, base.gpuMsP50, 2) : '—', r.gpuMsP95 ?? '—', r.frameMsP95, r.mainThreadMsP50, r.drawCalls, r.trianglesK, r.canvas, solverShort(r), r.power ?? '—']), ['l']));
    lines.push('');
    for (const r of featureRows.filter((x) => x.remeasured)) lines.push(`† Measured again later in the session: ${r.remeasured}.`, '');
  }

  if (failures.length) {
    lines.push('### Failures', '');
    for (const r of failures) lines.push(`- **${r.setting} · ${r.screen}:** ${r.error} (the page was on \`${r.state?.screen ?? '?'}\`; the survey reloaded and went on).`);
    lines.push('');
  }
}

writeFileSync(OUT, `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trim()}\n`);
console.log(`wrote ${OUT} from ${runs.length} run(s)`);
