"""Read-only independent terminal-capture integrity/history/chronology analysis."""
from pathlib import Path
import base64,hashlib,json,math,struct
W=Path('/private/tmp/tube-bounded-c-carrier-support-native-20261004');OUT=W/'candidate-first';N=Path(__file__).resolve().parent
checks=[];inputs={}
def pin(p):
 p=Path(p).resolve();b=p.read_bytes();return {'file':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def keep(p):
 row=pin(p);inputs[row['file']]=row;return row
def exact(row):
 q=keep(row['file']);assert q==row,row['file'];return q
def test(name,condition):
 assert condition,name;checks.append({'name':name,'pass':True})
def load(p):keep(p);return json.loads(Path(p).read_text())
def f32(v):return struct.unpack('<f',struct.pack('<f',v))[0]
def finite(v):return type(v) in (int,float) and math.isfinite(v)
def safe(v):return type(v) is int and 0<=v<=9007199254740991
owner=load(W/'candidate-first-owner.json');r=load(OUT/'report.json');seal=load(W/'seal.json');ready=load(W/'readiness.json');build=load(W/'root-complete-build-result.json');sourcecheck=load(W/'new-source-contract-checks.json');launcher=load(OUT/'launcher.json');keep(W/'candidate-first-owner.log')
test('terminal owner and capture successful, recorded exit0',owner['complete'] and owner['exitCode']==0 and owner['firstFailure'] is None and r['complete'] and r['firstFailure'] is None)
test('owner declared180s/168s/7s caps and actual elapsed within limits',owner['elapsedSeconds']<=180 and owner['cleanupElapsedSeconds']<=7 and owner['wholeSeconds']==180 and owner['commandSeconds']==168 and owner['cleanupSeconds']==7)
test('recorded owned ports initially and finally closed; no remaining owned PIDs',owner['ownedPortsInitiallyClosed']=={'4299':True,'9709':True} and owner['closedPorts']=={'4299':True,'9709':True} and not owner['remainingOwnedPids'] and owner['independentClosureValid'])
test('recorded protected4310/4311 closed4312open preserved',owner['protectedStatesInitially']==owner['protectedStatesFinally']=={'4310':True,'4311':True,'4312':False} and owner['protectedPortsPreserved'] and owner['protectedPortsStillOpen']['4312'] is True)
test('native/launcher record Chrome and movie cleanup',r['chromeClosed'] and launcher['ownedChromeClosed'] and launcher['portProof']['closed'] is True and r['video']['tracksStopped'] and r['videoCleanup']['tracksStopped'])
test('owner seal hash and source/build/helper postcheck agree',owner['sealSha256']==keep(W/'seal.json')['sha256'] and owner['sourceBuildHelpersPostUnchanged'] and seal['complete'] and seal['schema']=='bounded-C-carrier-support-root-seal/v1')
exact(ready['helperPinsManifest']);helper_manifest=load(W/'helper-pins.json');test('42readiness helper pins equal exact manifest',helper_manifest==ready['helperPins'] and len(helper_manifest)==42)
for p in helper_manifest:exact(p)
for p in seal['helperPins']:exact(p)
test('all frozen helper/sealed input bytes match independently',True)
a=seal['arms']['candidate'];exact(a['rootBuildManifest']);test('actual candidate source581/assets49/build identity equal seal and readiness',a['sourcePins']==build['sourcePins'] and a['assetPins']==build['assetPins'] and a['buildId']==build['buildId'] and len(build['sourcePins'])==ready['sourcePins']==581 and len(build['assetPins'])==ready['assets']==49 and build['terminal'] and build['exitCode']==0 and build['sourceUnchangedAfterBuild'])
for p in build['sourcePins']+build['assetPins']:exact(p)
for k in ('rootPartialBuildResult','rootOriginalBuildResult','priorStaticAssetsSeal'):exact(build[k])
for p in build['builtAssetPins']:exact(p)
for row in build['staticComposition']['references']+build['staticComposition']['overlap']:
 exact(row['source']);exact(row.get('frozenCopy',row.get('sameBuiltAsset')))
test('actual complete composition21fresh28additional2identicaloverlap',build['staticComposition']['newBuildAssets']==21 and build['staticComposition']['additionalStaticAssets']==28 and build['staticComposition']['identicalOverlap']==2 and len(build['assetPins'])==49)
sread=load(ready['carrierSourceReadiness']['file']);exact(ready['carrierSourceReadiness']);exact(sread['sourcePinsManifest']);sp=load(sread['sourcePinsManifest']['file']);test('582source readiness inventory differs from actual581by declared research input',len(sp['pins'])==len(sread['sourcePins'])==582 and sp['pins']==sread['sourcePins'])
for p in sp['pins']:exact({'file':str(Path(sread['sourceRoot'])/p['path']),'bytes':p['bytes'],'sha256':p['sha256']})
allpaths={p['path'] for p in sp['pins']};buildpaths={str(Path(p['file']).relative_to(sread['sourceRoot'])) for p in build['sourcePins']};test('build only omission exactly recorded research JSON',allpaths-buildpaths=={'docs/research/water-physics/notes/round6-tube-profiles/data/padang-ray-L11-profiles.json'} and not buildpaths-allpaths)
for k in ('priorAirSeal','priorFullsheetSeal','priorParallelSeal','priorMouthSeal','priorPhysicalMouthSeal','physicalSourceReadiness','carrierSourceReadiness','priorFailedAgeGate','sourceContractCheck','publicHistoryContract','releaseStressReadiness'):exact(seal[k])
for k in ('priorFailedParallel','priorFailedMouth'):
 for p in seal[k].values():exact(p)
test('all old failed receipt provenance remains exact without retroacceptance',True)
assets={str(Path(p['file']).relative_to(build['frozenDist'])):p for p in build['assetPins']}
for name,p in owner['served'].items():test('served pin '+name,{'bytes':assets[name]['bytes'],'sha256':assets[name]['sha256']}==p)
test('media inventory exactly4PNG+1movie separate from snapshots',len(r['artifacts'])==5 and {p['file'] for p in r['artifacts']}=={str(i)+'-'+c['label']+'.png' for i,c in enumerate(r['checkpoints'])}|{'moving-C.webm'} and r['mediaInventorySeparateFromOptionalLoftSnapshots'])
media=[]
for p in r['artifacts']:
 q=exact({**p,'file':str(OUT/p['file'])});media.append(q)
 if p['file'].endswith('.png'):
  b=Path(q['file']).read_bytes();test('PNG signature/dimensions '+p['file'],b[:8]==b'\x89PNG\r\n\x1a\n' and struct.unpack('>II',b[16:24])==(1708,879))
 else:test('movie exact EBML payload',Path(q['file']).read_bytes()[:4]==bytes.fromhex('1a45dfa3') and p['sha256']==r['video']['sha256'] and p['bytes']==r['video']['bytes'])
test('report/media byte caps respected',keep(OUT/'report.json')['bytes']<=32*1024*1024 and r['pngBytes']==sum(p['bytes'] for p in r['artifacts'] if p['file'].endswith('.png'))<=48*1024*1024 and r['video']['bytes']<=16*1024*1024)
vertex={'positions':3,'normals':3,'mask':1,'lift':1,'sheet':1,'sheetWeight':1,'sheetBack':1,'throat':4};nonmutation={'snapshotClockStatusWordsUnchanged','normalAndDiagnosticCameraUnchanged','normalActorControlsAndMeshUnchanged','allActiveLoftWordsUnchanged','drawnSurfaceWordsAndEpochUnchanged','drawGenerationUnchanged'};snapshots=[]
test('two only declared snapshot epochs initial/firstphase2',len(r['loftSnapshots'])==2 and [s['label'] for s in r['loftSnapshots']]==['initial','first-phase2'])
for s in r['loftSnapshots']:
 q=exact({'file':str(OUT/s['file']),'bytes':s['bytes'],'sha256':s['sha256']});full=load(q['file']);c=next(c for c in r['checkpoints'] if c['label']==s['label']);o=c['observation'];ct=full['counts']
 test('snapshot '+s['label']+' exact complete metadata/epoch/nonmutation',full['schema']==s['schema']=='bounded-C-complete-drawn-loft-words/v1' and full['label']==s['label'] and full['available'] and c['loftSnapshot']==s and full['counts']==s['counts'] and full['epoch']==s['epoch'] and full['epoch']['step']==o['step'] and full['epoch']['movingStep']==o['movingStep'] and full['epoch']['seaTime']==o['seaTime'] and full['epoch']['surfaceRevision']==o['drawEpoch']['surfaceRevisionAfter'] and full['epoch']['drawnWaterTime']==o['seaTime'] and full['nonmutation']==s['nonmutation'] and set(full['nonmutation'])==nonmutation and all(full['nonmutation'].values()) and full['arrayIdentitiesAndWordsUnchanged'] and not full['unusedCapacityIncluded'] and not full['geometryOrCameraSearch'] and not full['perFragmentOwnershipOrVisibilityClaim'] and not full['openingOrBodyPassageClaim'])
 test('snapshot '+s['label']+' within declared caps',q['bytes']<=6*1024*1024 and full['rawBytes']<=4*1024*1024 and ct['slices']<=300 and ct['vertices']<=40200 and ct['indices']<=240000)
 raw=0;arraypins={}
 for key,v in full['arrays'].items():
  assert {k:x for k,x in v.items() if k!='data'}==s['arrayManifest'][key];count=vertex[key]*ct['vertices'] if key in vertex else ct['indices'] if key=='indices' else ct['slices'];size={'Float32Array':4,'Int32Array':4,'Uint32Array':4,'Uint8Array':1}[v['dtype']];words=base64.b64decode(v['data'],validate=True)
  assert v['count']==count and v['byteLength']==count*size==len(words) and v['littleEndian'] is True and v['encoding']=='base64-exact-active-typed-array-words';raw+=len(words);arraypins[key]={'dtype':v['dtype'],'count':count,'bytes':len(words),'sha256':hashlib.sha256(words).hexdigest()}
 assert raw==full['rawBytes']==s['rawBytes'] and set(full['arrays'])==set(s['arrayManifest']) and len(full['arrays'])==37
 test('snapshot '+s['label']+'37arrays strict base64 dtype/endian/count exact active words',True)
 snapshots.append({'label':s['label'],'payload':q,'epoch':s['epoch'],'counts':ct,'rawBytes':raw,'arrays':arraypins,'normalsMeaning':full['normalsMeaning'],'notFragmentOrGBufferNormals':True})
test('snapshot total exact bytes and cap',r['snapshotBytes']==sum(s['payload']['bytes'] for s in snapshots)<=12*1024*1024)
obs=r['observations'];joined=[o for o in obs if not o['missing']];last=obs[-1];initial=obs[0]['initialPublicPointIdentity'];ids=initial['pointIDs'];fp=['x','footHeight','footDepth','throwZ','jetPace','jetBase','jetAt','jetUntil'];rawkeys={'x':'x','z':'z','front':'front','sigma':'sigma','tau':'tau','footHeight':'footHeight','footDepth':'footDepth','throwZ':'throwZ'};proofs=[];historycases=[]
test('69ordinary observations and frame requests moving0..68',len(obs)==len(r['videoRequests'])==69 and [o['movingStep'] for o in obs]==list(range(69)) and r['video']['physicsAdvances']==68 and r['video']['requestFrameCount']==69)
test('ordinary clock increments and declared neutral controls',all(abs(o['seaTime']-obs[0]['seaTime']-o['movingStep']/60)<1e-7 for o in obs) and r['install']['normalCameraAndControlsUntouched'] is True)
test('fixed station locked Eulerian identity stable throughout',ids==[158,159] and [p['column'] for p in initial['points']]==[87,88] and [p['x'] for p in initial['points']]==[15,17] and all(o['locked']==r['selection']['locked'] and o['locked']['stationIdentity']=='fixed-Eulerian-solver-column-crest-station' and not o['locked']['materialTrajectoryClaim'] for o in obs))
exports=last['publicExportEvidence'];test('actual5publicexports 1initial3rename1direct with all purity flags',len(exports)==5 and sum(e['reason'].startswith('first-positive') for e in exports)==1 and all(all(e[k] for k in ('snapshotClockStatusWordsUnchanged','normalActorPoseAndCameraUnchanged','surfaceWordsAndEpochUnchanged','drawGenerationUnchanged','exactLoftWordsUnchanged')) and not e['solverArraysDecodedOrRetained'] and abs(e['exportedSeaTime']-e['seaTime'])<1e-7 and e['solverTime']+e['seaTimeOffset']==e['exportedSeaTime'] for e in exports))
def check_identity(identity,step):
 assert identity['qualified'] and identity['pointIDs']==ids and all(identity['gates'].values())
 for i,(p,q,h) in enumerate(zip(identity['points'],initial['points'],identity['carrierHistories'])):
  assert p['id']==q['id'] and p['column']==q['column'] and all(finite(p[k]) and p[k]==q[k] for k in fp) and finite(p['tau']) and p['tau']>=q['tau']>=0 and p['jetPace']>0
  g=p['carrierSupport'];own=p['tau']<p['jetUntil'];retained=not own and any(t['potentiallyLive'] for t in g['incidents']);geometric=own or bool(g['policy']=='bounded-C-incident-support/v1' and g['atTau']==p['tau'] and g['geometricPaceActive'] and finite(p['jetPace']) and finite(p['jetBase']))
  assert g['policy']=='bounded-C-incident-support/v1' and g['atTau']==p['tau'] and finite(g['solverTime']) and g['ownPocketAlive']==own and g['retainedForGeometry']==retained and g['geometricPaceActive']==(own or retained) and g['state']==('own-pocket' if own else 'incident-support' if retained else 'released') and geometric
  assert len(g['incidents'])<=2 and len(set(t['otherId'] for t in g['incidents']))==len(g['incidents'])
  for t in g['incidents']:assert safe(t['otherId']) and t['otherId']!=p['id'] and safe(t['front']) and t['front']==p['front'] and all(finite(t[k]) and t[k]>0 for k in ('boundSeconds','maxScale','maxAuthoredTD')) and finite(t['minimumPacketAge']) and safe(t['partitions']) and t['partitions']>0 and t['potentiallyLive']==(t['minimumPacketAge']<t['boundSeconds'])
  assert h['contractValid'] and not h['immutableFingerprint'] and not h['solverTimeEqualityRequired'] and h['history']==g
  historycases.append({'step':step,'pointID':p['id'],'front':p['front'],'tau':p['tau'],'ownUntil':p['jetUntil'],'ownPocketAlive':own,'retainedForGeometry':retained,'geometricPaceActive':geometric,'atTauExact':g['atTau']==p['tau'],'refreshSolverTime':g['solverTime'],'placementZResidual':p['z']-(p['jetBase']+p['jetPace']*p['tau']),'incidents':g['incidents']})
check_identity(initial,0);renames=[]
for o in obs:
 if o['lineageDecision'] and o['lineageDecision'].get('componentLineageEvent'):
  e=o['lineageDecision'];passing=[c for c in e['testedCandidates'] if c['qualified']];assert e['qualifiedCount']==len(passing)==1 and e['provenOrderedInternalPointIDs']==ids and not e['DTEqualityRequired'] and not e['materialTrajectoryClaim'] and e['carrierSupportIsDynamicNotImmutableFingerprint'];c=passing[0];assert c['front']==o['currentFront'] and all(c['gates'].values());check_identity(c['publicPointIdentity'],o['movingStep']);renames.append({'movingStep':o['movingStep'],'beforeFront':e['beforeFront'],'afterFront':e['afterFront'],'qualifiedCount':1,'testedCount':len(e['testedCandidates']),'IDs':ids,'maximumAbsoluteAgeRefitResidual':max(abs(a['observedRefitAgeResidual']) for a in c['ages'])})
test('three actual rename proofs retain exact IDs/columns/fingerprints with current dynamic carrier history',len(renames)==3)
seen=set()
for e in last['carrierHistoryEvidence']:
 assert e['qualified'] and all(e['gates'].values()) and e['directProofStatus']=='exercised-current-public-carrier-history' and not e['materialTrajectoryClaim'] and not e['solverTimeEqualityRequired'] and not e['leaseDurationOrDTGate'] and not e['geometryOrCameraSteering'];check_identity(e['publicPointIdentity'],e['movingStep']);assert not seen.intersection(e['triggerPointIDs']);seen.update(e['triggerPointIDs'])
 for t in e['triggerPackets']:
  i=ids.index(t['pointID']);p=e['publicPointIdentity']['points'][i];q=initial['points'][i];raw=t['raw'];assert t['initialImmutableJetUntil']==q['jetUntil'] and raw['tau']>f32(q['jetUntil']) and finite(raw['pace']) and raw['pace']>0 and all(raw[k]==f32(p[v]) for k,v in rawkeys.items()) and raw['pace']==f32(p['jetPace']) and not p['carrierSupport']['ownPocketAlive'] and p['carrierSupport']['retainedForGeometry']
  o=obs[e['movingStep']];before=obs[e['movingStep']-1];prev=next(v for v in before['mapping']['rawRows'] if v['x']==p['x']);assert not o['missing'] and o['openingPresent'] is False and o['loftStation']['bracket']
  proofs.append({'movingStep':e['movingStep'],'pointID':p['id'],'column':p['column'],'x':p['x'],'currentFront':p['front'],'sourceTau':p['tau'],'immutableJetUntil':p['jetUntil'],'sourceExpiredAmount':p['tau']-p['jetUntil'],'rawF32Tau':raw['tau'],'immutableUntilF32':f32(p['jetUntil']),'strictF32TriggerMargin':raw['tau']-f32(p['jetUntil']),'sourceHistory':p['carrierSupport'],'sourceZ':p['z'],'rawZ':raw['z'],'beforeRawZ':prev['z'],'rawZTransition':raw['z']-prev['z'],'beforeRawTau':prev['tau'],'rawTauTransition':raw['tau']-prev['tau'],'observedRawTauRefitResidualToDT':raw['tau']-prev['tau']-1/60,'observedRawZResidualToPaceDT':raw['z']-prev['z']-raw['pace']/60,'ownPhysicalLifetimeExtended':False,'immutableFingerprintExact':True,'afterLocalAirLossStillJoined':True,'actualPublicHistoryProven':True})
test('one actual expired-own incident-only proof ID158 step63 after airloss; no second point wait',len(proofs)==1 and proofs[0]['pointID']==158 and proofs[0]['movingStep']==63 and last['carrierHistoryProbe']['perOriginalPoint'][0]['publicLeaseProof'] and last['carrierHistoryProbe']['perOriginalPoint'][1]['status']=='not-exercised-before-honest-station-or-identity-loss' and not last['carrierHistoryProbe']['perOriginalPoint'][1]['publicLeaseProof'])
test('ID159never crosses conservative F32trigger before honest join loss',all(next(v for v in o['mapping']['rawRows'] if v['x']==17)['tau']<=f32(initial['points'][1]['jetUntil']) for o in obs))
test('recorded render/export/snapshot draw epoch purity and ray invariants',all(o['drawEpoch']['drawnWaterTimeMatchesCurrentSnapshot'] and o['drawEpoch']['snapshotIdentityUnchanged'] and o['drawEpoch']['physicsClockUnchanged'] and o['drawEpoch']['supportedOrder']==['water.update','mode.drawBarrel'] and o['rayDiagnostics']['rayInvalidIntervals']==0 and (not o['rayDiagnostics']['joinedRowPairs'] or o['rayDiagnostics']['rayMinAdvance']>0 and o['rayDiagnostics']['rayMaxBlend']==1) and (o['movingStep']==0 or o['renderEvidence']['observedRowIndexPositionWordsUnchanged'] and o['renderEvidence']['drawEpochUnchanged']) for o in obs))
phase_changes=[{'movingStep':o['movingStep'],'rows':[v['slicePhase'] for v in o['rows']]} for i,o in enumerate(joined) if i==0 or [v['slicePhase'] for v in o['rows']]!=[v['slicePhase'] for v in joined[i-1]['rows']]]
airloss=next(o['movingStep'] for o in joined if o['openingPresent'] is False);phase=next(o['movingStep'] for o in joined if any(v['slicePhase']==2 for v in o['rows']));test('actual firstphase247/airloss56/joinloss68 chronology',phase==r['firstObservedPhase2']['movingStep']==47 and airloss==56 and last['movingStep']==68 and last['stopReason']==r['stop']['reason']=='loft-join-absent' and last['loftStation']['bracket'] is None and last['mapping']['reason'] is None and last['cameraHeldAtLastValidPose'] and not last['retirementClaim'] and not r['stop']['physicalDeathClaim'])
def landmarks(o):
 a,b=o['rows'];t=o['loftStation']['bracket']['t'];return {k:[a[k][i]+t*(b[k][i]-a[k][i]) for i in range(3)] for k in ('crest','cap','toe')}
fixed=[];jumps=[]
for o in joined:
 marks=landmarks(o);assert abs(marks['crest'][0]-o['locked']['stationX'])<1e-12
 fixed.append({'movingStep':o['movingStep'],'currentFront':o['currentFront'],'rows':[v['row'] for v in o['rows']],'t':o['loftStation']['bracket']['t'],'weights':[v['sliceWeight'] for v in o['rows']],'landmarks':marks})
for a,b in zip(fixed,fixed[1:]):jumps.append({'beforeStep':a['movingStep'],'afterStep':b['movingStep'],'before':a,'after':b,'deltas':{k:[b['landmarks'][k][i]-a['landmarks'][k][i] for i in range(3)] for k in ('crest','cap','toe')}})
maxima={k:max(jumps,key=lambda v:abs(v['deltas'][k][2])) for k in ('crest','cap','toe')}
rawtransitions=[]
for a,b in zip(obs,obs[1:]):
 rawtransitions.append({'beforeStep':a['movingStep'],'afterStep':b['movingStep'],'points':[{'pointID':ids[i],'column':initial['points'][i]['column'],'x':initial['points'][i]['x'],'before':a['mapping']['rawRows'][i],'after':b['mapping']['rawRows'][i],'deltaZ':b['mapping']['rawRows'][i]['z']-a['mapping']['rawRows'][i]['z'],'deltaTau':b['mapping']['rawRows'][i]['tau']-a['mapping']['rawRows'][i]['tau']} for i in range(2)]})
rawmax={str(ids[i]):max(({'beforeStep':v['beforeStep'],'afterStep':v['afterStep'],**v['points'][i]} for v in rawtransitions),key=lambda v:abs(v['deltaZ'])) for i in range(2)}
openobs=[o for o in joined if o['openingPresent']];mouth={'openObservationCount':len(openobs),'columnQueries':sum(len(o['mouth']['attempts']) for o in openobs),'insideSightlineClear':sum(not o['cameraOcclusion']['indexedLoftOccluded'] for o in openobs),'externalSightlineObstructed':sum(o['mouth']['exterior']['fullSightline']['indexedLoftOccluded'] for o in openobs),'shoreward2mObstructed':sum(o['mouth']['shorewardContinuation']['fullSightline']['indexedLoftOccluded'] for o in openobs),'noVisibilityAcceptance':True}
test('bounded mouth24queries each open observation and failed exterior rays retained',mouth['openObservationCount']==56 and mouth['columnQueries']==56*24 and mouth['insideSightlineClear']==56 and mouth['externalSightlineObstructed']==56 and mouth['shoreward2mObstructed']==56 and all(o['mouth']['maximumColumnQueries']==24 and not o['mouth']['externalEntranceClaim'] and not o['mouth']['continuousAirCorridorClaim'] and not o['mouth']['bodyPassageClaim'] and o['mouth']['exterior']['poseRetries']==0 for o in openobs))
retainedrows=[v for v in last['allFrontRowsOnLoss'] if v['sliceFront']==last['currentFront']];firstrow=retainedrows[0];last_detail={'rawBracketPresent':True,'loftBracketAbsent':True,'cameraHeldAtStep':obs[-2]['movingStep'],'firstRetainedCurrentFrontRow':firstrow,'retainedFrontRowCount':len(retainedrows),'firstRetainedXMinusLockedX':firstrow['crest'][0]-last['locked']['stationX'],'notPhysicalDeath':True}
for p in list(inputs.values()):assert pin(p['file'])==p,p['file']
test('all consumed original inputs unchanged at analysis end',True)
result={'schema':'bounded-C-carrier-terminal-native-evidence-review/v1','complete':True,'readOnly':True,'resourceUse':{'resourcesStarted':False,'portsProbed':False,'sourceEdits':False,'helperOrCaptureEdits':False,'GitMutations':False,'testsOrBuildsRerun':False},'checks':checks,'checkCount':len(checks),'inputPins':list(inputs.values()),'integritySummary':{'sourceBuildPins':581,'sourceReadinessPins':582,'assetPins':49,'helperPins':42,'sealedHelperPins':len(seal['helperPins']),'servedAssets':len(owner['served']),'mediaPayloads':len(media),'snapshotPayloads':len(snapshots)},'ownerSummary':{k:owner[k] for k in ('complete','exitCode','elapsedSeconds','cleanupElapsedSeconds','closedPorts','remainingOwnedPids','protectedStatesInitially','protectedStatesFinally','independentClosureValid','protectedPortsPreserved')},'ordinaryChronology':{'observations':69,'physicsAdvances':68,'physicalSeconds':r['video']['physicalSeconds'],'firstPhase2':phase,'phaseChanges':phase_changes,'firstAirLoss':airloss,'joinLoss':68,'cameraLastValidStep':67,'frameRequests':69,'encodedFrameCountOrPlaybackRateClaim':False,'selectedLocked':r['selection']['locked'],'retirementOrPhysicalDeathClaim':False},'publicExports':exports,'actualDirectHistoryProofs':proofs,'perOriginalPointProbeOutcome':last['carrierHistoryProbe']['perOriginalPoint'],'publicHistoryCases':historycases,'renameProofs':renames,'fixedStationLandmarks':fixed,'maximumAbsoluteFixedStationZChanges':{k:{'beforeStep':v['beforeStep'],'afterStep':v['afterStep'],'deltaZ':v['deltas'][k][2],'beforeLandmark':v['before']['landmarks'][k],'afterLandmark':v['after']['landmarks'][k],'beforeRows':v['before']['rows'],'afterRows':v['after']['rows'],'beforeWeights':v['before']['weights'],'afterWeights':v['after']['weights']} for k,v in maxima.items()},'maximumRawColumnZChanges':rawmax,'carrierTransitionRawBeforeAfter':rawtransitions[60:],'mouthDiagnostics':mouth,'terminalLoss':last_detail,'mediaPins':media,'snapshotIntegrity':snapshots,'inheritedGpuFixturesAreNotNewLeaseProof':True,'directPublicHistoryProvesGeometricCarrierNotOwnPhysicalFunding':True,'publicIncidentBoundReportedNotIndependentlyRecomputedFromSourceProvider':True,'otherIncidentIDsOutsideSelectedTwoNotIndependentlyLinkedByThisHeaderSubset':True,'crossCandidateMatchedStateEquivalence':False,'fullGeometryAnalysisOwnedByOtherWorker':True,'pixelsNotViewedByThisWorker':True,'acceptance':{'tubeQuality':False,'mouth':False,'bodyPassage':False,'FPS':False,'production':False}}
(N/'analysis.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'complete':True,'checks':len(checks),'inputCount':len(inputs),'proofs':proofs,'maxZ':result['maximumAbsoluteFixedStationZChanges'],'mouth':mouth,'snapshotBytes':r['snapshotBytes'],'output':str(N/'analysis.json')}))
