from pathlib import Path
import runpy,json,hashlib
W=Path('/private/tmp/tube-grey-band-ownership-proposal-20261005');A=Path('/private/tmp/tube-authored-mask-native-20261005');O=Path('/private/tmp/tube-sheet-fill-native-20261005')
helper=Path('/private/tmp/tube-mask-author-support-analysis-20261005.py');f=runpy.run_path(str(helper));pin=lambda p:{'file':str(p),'bytes':len(p.read_bytes()),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
choice=json.loads((W/'sample-choice.json').read_text());pixels=[tuple(item['pixel'])for item in choice['samplesTopLeft0Based']]
report=json.loads((A/'candidate-first/report.json').read_text());inputs=json.loads((A/'inputs.json').read_text());snapshot=json.loads(f['read_pin'](report['referenceLoft']));arrays={name:f['decode'](words)for name,words in snapshot['arrays'].items()};camera=inputs['fixedCameras']['interior']
files={'combined':A/'candidate-first/interior-rich-combined-mask-and-sheet-fill-A.png','maskRich':A/'candidate-first/interior-rich-authored-support.png','maskRegion':A/'candidate-first/interior-region-authored-support.png','regionOriginal':A/'candidate-first/interior-region-original.png','baseline':A/'candidate-first/interior-rich-original.png','opticalA':O/'candidate-first/interior-rich-sheet-fill-A.png','opticalB':O/'candidate-first/interior-rich-throat-bypass-B.png'}
images={key:f['png_pixels'](path.read_bytes(),pixels)[1]for key,path in files.items()};positions,indices=arrays['positions'],arrays['indices'];results=[]
for sample in choice['samplesTopLeft0Based']:
 pixel=tuple(sample['pixel']);origin,direction,clip,ndc=f['ray'](camera,(1708,879),pixel);hits=[]
 for off in range(0,len(indices),3):
  ids=indices[off:off+3];points=[positions[3*v:3*v+3]for v in ids];hit=f['intersect'](origin,direction,*points)
  if hit is not None and clip[0]<=hit[0]<=clip[1]:
   d=f['describe'](arrays,off,ids,hit,origin,direction,clip);cross=f['cross'](f['sub'](points[1],points[0]),f['sub'](points[2],points[0]));normalSum=tuple(sum(arrays['normals'][3*v+c]for v in ids)for c in range(3));facing=f['dot'](cross,normalSum)
   actualCross=tuple(-v if facing<0 else v for v in cross);d['facesOutWindingSwap']=facing<0;d['crossDotAverageNormal']=facing;d['actualWindingCrossDotRay']=f['dot'](actualCross,direction);d['inferredRasterFrontFacingAssumingIdentityWorldTransform']=d['actualWindingCrossDotRay']<0;hits.append(d)
 hits.sort(key=lambda item:(item['distanceMetres'],item['triangle']));results.append({**sample,'encodedRGBA':{key:rgba[pixel]for key,rgba in images.items()},'rayOrigin':origin,'rayDirection':direction,'ndc':ndc,'insideFrustumForwardLoftHits':len(hits),'nearestThreeSavedLoftHits':hits[:3]})
result={'schema':'grey-band-saved-pixel-ray-inspection/v1','executedOfflineReadOnly':True,'nativeExecution':False,'productionChanged':False,'choicePin':pin(W/'sample-choice.json'),'helperPin':pin(helper),'authorityPins':[pin(A/'owner.json'),pin(A/'candidate-first/report.json'),pin(A/'inputs.json'),report['referenceLoft']]+[pin(path)for path in files.values()],'camera':camera,'geometryEpoch':snapshot['epoch'],'samples':results,'limits':['Four predeclared points only; no pixel/geometry/epoch search.','Saved double-sided triangle rays omit discard, stencil, depth occlusion by other drawables, shader displacement of ordinary water and raster multisampling.','Repaired loft winding inference assumes its source-authored identity world transform; actual runtime gl_FrontFacing is not recorded.','Actual encoded PNG samples are observed; ray hits cannot identify final visible drawable.']}
(W/'saved-pixel-ray-inspection.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps({'samples':[{'pixel':item['pixel'],'role':item['role'],'rgba':item['encodedRGBA'],'loftHits':item['insideFrustumForwardLoftHits'],'nearest':[{'triangle':d['triangle'],'distance':d['distanceMetres'],'mask':d['interpolatedAuthoredMask'],'region':d['interpolatedRegionLinearRGB'],'phase':[v['phase']for v in d['vertices']]}for d in item['nearestThreeSavedLoftHits']]}for item in results]},indent=2))
