// Generated by `npm run lesson:wave` — do not edit.
import type { LessonWave } from './lessonWave';

export const LESSON_WAVES: readonly LessonWave[] = [
  {
    "stage": 2,
    "config": {
      "spot": "pool",
      "seed": 1,
      "significantHeight": 1.145512985522207,
      "peakPeriod": 10,
      "directionDegrees": 0,
      "spreading": 1000,
      "tide": 0,
      "windSpeed": 0,
      "componentCount": 1
    },
    "assets": {
      "pocket": "lessons/pool-s2-pocket.sea",
      "caught": "lessons/pool-s2-caught.sea",
      "waiting": "lessons/pool-s2-waiting.sea"
    },
    "placements": {
      "pocket": {
        "x": 28.11,
        "z": -161.82,
        "heading": 0.711,
        "speed": 8.42,
        "phase": "standing"
      },
      "caught": {
        "x": 27.19,
        "z": -176.2,
        "heading": 0.236,
        "speed": 1.81,
        "phase": "prone"
      },
      "waiting": {
        "x": 26.92,
        "z": -188.34,
        "heading": -0.048,
        "speed": 0.48,
        "phase": "prone"
      }
    },
    "provisional": false,
    "checks": {
      "pocket": "stood 4.3 s (attempt 12)",
      "caught": "stood 9.6 s (attempt 12)",
      "waiting": "stood 2.6 s (attempt 5)"
    }
  }
];
