// Generated by `npm run lesson:wave` — do not edit.
import type { LessonWave } from './lessonWave';

export const LESSON_WAVES: readonly LessonWave[] = [
  {
    "stage": 2,
    "config": {
      "spot": "canyon",
      "seed": 1,
      "significantHeight": 1.4,
      "peakPeriod": 12,
      "directionDegrees": 10,
      "spreading": 40,
      "bandwidth": 0.08,
      "tide": 0,
      "windSpeed": 0,
      "componentCount": 64
    },
    "assets": {
      "pocket": "lessons/canyon-s2-pocket.sea",
      "caught": "lessons/canyon-s2-caught.sea",
      "waiting": "lessons/canyon-s2-waiting.sea"
    },
    "placements": {
      "pocket": {
        "x": -8.2,
        "z": -48.52,
        "heading": -0.519,
        "speed": 0.25,
        "phase": "standing"
      },
      "caught": {
        "x": -6.29,
        "z": -72.89,
        "heading": -0.627,
        "speed": 2.39,
        "phase": "prone"
      },
      "waiting": {
        "x": 0.47,
        "z": -84.68,
        "heading": 0.132,
        "speed": 0.97,
        "phase": "prone"
      }
    },
    "provisional": false,
    "checks": {
      "pocket": "stood 6.4 s (attempt 1)",
      "caught": "stood 6.1 s (attempt 18)",
      "waiting": "stood 3.8 s (attempt 4)"
    }
  }
];
