// Generated by `npm run lesson:wave` — do not edit.
import type { LessonWave } from './lessonWave';

export const LESSON_WAVES: readonly LessonWave[] = [
  {
    "stage": 2,
    "config": {
      "spot": "canyon",
      "seed": 1,
      "significantHeight": 1.4,
      "peakPeriod": 12,
      "directionDegrees": 10,
      "spreading": 40,
      "bandwidth": 0.08,
      "tide": 0,
      "windSpeed": 0,
      "componentCount": 64
    },
    "assets": {
      "pocket": "lessons/canyon-s2-pocket.sea",
      "caught": "lessons/canyon-s2-caught.sea",
      "waiting": "lessons/canyon-s2-waiting.sea"
    },
    "placements": {
      "pocket": {
        "x": 2.94,
        "z": -43.55,
        "heading": 0.435,
        "speed": 9.14,
        "phase": "standing"
      },
      "caught": {
        "x": 3.87,
        "z": -64.32,
        "heading": 0.065,
        "speed": 1.97,
        "phase": "prone"
      },
      "waiting": {
        "x": 1.03,
        "z": -84.26,
        "heading": 0.011,
        "speed": 1.29,
        "phase": "prone"
      }
    },
    "provisional": false,
    "checks": {
      "pocket": "stood 3.8 s (attempt 17)",
      "caught": "stood 4.9 s (attempt 4)",
      "waiting": "stood 4.6 s (attempt 4)"
    }
  }
];
