/**
 * Legacy board baseline (board plan B0, wave plan P4b): scripted legacy runs
 * across seeds, presets and steering, written to docs/research/board-baseline.md.
 * The new board (P4c onward) is compared against these numbers; they describe
 * the legacy game, not real surfing.
 *
 *   npm run report:board-baseline
 */
import { writeFileSync } from 'node:fs';
import { LEGACY_BOARD, REFERENCE_BOARD, REFERENCE_RIDER, referenceFlotation } from '../src/physics/boardReference';
import { LEGACY_PRESETS, runTrace, type TraceScenario } from '../src/physics/boardTrace';
import type { BoardPhysics } from '../src/physics/BoardPhysics';

const physics = { paddleForce: 14, boardResponse: 1 };
const fixed = (value: number | null, digits = 1) => (value === null ? '—' : value.toFixed(digits));
const started = Date.now();

const catchRows: string[] = [];
for (let seed = 1; seed <= 12; seed += 1) {
  const result = runTrace({ name: `training ${seed}`, seed, wave: LEGACY_PRESETS.training, physics, frames: 1200 });
  catchRows.push(`| ${seed} | ${fixed(result.catchTime)} s | ${fixed(result.rideTime)} s | ${result.rideDistance.toFixed(1)} m | ${fixed(result.peakSpeed)} m/s | ${result.state} |`);
}

const steering: Record<string, (board: BoardPhysics) => number> = {
  none: () => 0,
  carve: (board) => Math.sin(board.time * 0.72) * 0.45,
  'hard turn': () => 1,
};
const rideRows: string[] = [];
for (const [spot, wave] of Object.entries(LEGACY_PRESETS)) {
  for (const [style, steer] of Object.entries(steering)) {
    for (let seed = 1; seed <= 3; seed += 1) {
      const scenario: TraceScenario = { name: `${spot} ${style} ${seed}`, seed, wave: { ...wave, sustained: true }, physics, frames: 3600, steer };
      const result = runTrace(scenario);
      rideRows.push(`| ${spot} | ${style} | ${seed} | ${fixed(result.catchTime)} s | ${fixed(result.rideSeconds)} s | ${result.rideDistance.toFixed(1)} m | ${result.peakSpeed.toFixed(1)} m/s | ${result.peakTurnRate.toFixed(2)} rad/s | ${result.lowestBalance.toFixed(2)} | ${result.state}${result.fell ? ' · fell' : ''} |`);
    }
  }
}

const flotation = referenceFlotation();
const report = `# Legacy board baseline

Generated by \`npm run report:board-baseline\` on ${new Date().toISOString().slice(0, 10)} (board plan B0, wave plan P4b; reported, not asserted). Fixed 1/60 s steps; the input script paddles until the pop-up window, stands, then steers as listed. These numbers describe the legacy game: the next board (P4c onward) is compared against them, and none is a real-surfing target.

## Reference board and rider (recorded, not yet used)

| | Value | Source |
|---|---|---|
| Rider mass | ${REFERENCE_RIDER.mass} kg | ${REFERENCE_RIDER.source} |
| Board | ${REFERENCE_BOARD.length} × ${REFERENCE_BOARD.width} × ${REFERENCE_BOARD.thickness} m, ${(REFERENCE_BOARD.volume * 1000).toFixed(2)} L, ${REFERENCE_BOARD.mass} kg, ${REFERENCE_BOARD.fins} | ${REFERENCE_BOARD.source} |
| Flotation at rest | ${flotation.buoyantMass.toFixed(1)} kg of seawater: ${Math.round(flotation.unsupportedFraction * 100)} % of rider and board must come from planing lift when standing | derived |
| Legacy today | ${LEGACY_BOARD.renderedLength} m rendered board, ${LEGACY_BOARD.simulationMass} kg effective simulation mass, ${LEGACY_BOARD.riderMass} kg rider, contacts at ±(${LEGACY_BOARD.contactHalfWidth}, ${LEGACY_BOARD.contactHalfLength}) m | code |

## Catch on the default wave (Training, seeds 1–12, no steering)

| Seed | Catch (Get Up) | Riding from | Ride | Peak speed | Outcome |
|---|---:|---:|---:|---:|---|
${catchRows.join('\n')}

## Sustained rides (up to 60 s)

| Preset | Steering | Seed | Catch | Ride time | Ride | Peak speed | Peak path turn | Lowest balance | Outcome |
|---|---|---:|---:|---:|---:|---:|---:|---:|---|
${rideRows.join('\n')}

**Known limits.**
- The legacy wave speed is a slider value (its gravity is rescaled), catches and rides use timers and thresholds, and the board and rider share one effective mass. These are the behaviours P4c–P4f replace.
- "Peak path turn" is the travel heading's turn rate, not a detected maneuver; the board plan's event definitions (bottom turn, top turn) apply from P4d.
- The legacy traces are locked by golden hashes (\`BoardTrace.test.ts\`); this report summarises them over more seeds.

Run time: ${((Date.now() - started) / 1000).toFixed(0)} s.
`;
writeFileSync('docs/research/board-baseline.md', report);
console.error('wrote docs/research/board-baseline.md');
