/**
 * Per-spot rideability report (plan §4 item 11): runs the stage 1 surf zone
 * at the Wave Lab's default conditions for several seeds, samples the measured
 * peel once per peak period, and writes docs/research/rideability-report.md.
 *
 *   npm run report:rideability -- --seeds 3 --periods 20
 *   npm run report:rideability -- --spots point --direction 30 --spread 0 --out /tmp/point.md
 */
import { writeFileSync } from 'node:fs';
import { DEFAULT_PHYSICAL_SETTINGS, spreadingFor } from '../src/game/PhysicalMode';
import type { SpotName } from '../src/wave/Bathymetry';
import { PEEL_SKILL_MINIMUM } from '../src/wave/Breaking';
import { measureRideability, rideability, type PeelSample } from '../src/wave/Rideability';

const option = (name: string): string | undefined => {
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : undefined;
};
const argument = (name: string, fallback: number): number => Number(option(name) ?? fallback);
const seedCount = argument('seeds', 3);
const periods = argument('periods', 20);
const spots = (option('spots')?.split(',') ?? ['beach', 'point', 'reef', 'canyon']) as SpotName[];
const output = option('out') ?? 'docs/research/rideability-report.md';
const settings = {
  ...DEFAULT_PHYSICAL_SETTINGS,
  significantHeight: argument('hs', DEFAULT_PHYSICAL_SETTINGS.significantHeight),
  peakPeriod: argument('tp', DEFAULT_PHYSICAL_SETTINGS.peakPeriod),
  directionDegrees: argument('direction', DEFAULT_PHYSICAL_SETTINGS.directionDegrees),
  spread: argument('spread', DEFAULT_PHYSICAL_SETTINGS.spread),
};
const custom = settings.significantHeight !== DEFAULT_PHYSICAL_SETTINGS.significantHeight || settings.peakPeriod !== DEFAULT_PHYSICAL_SETTINGS.peakPeriod
  || settings.directionDegrees !== DEFAULT_PHYSICAL_SETTINGS.directionDegrees || settings.spread !== DEFAULT_PHYSICAL_SETTINGS.spread;
const percent = (share: number) => `${Math.round(share * 100)} %`;

const rows: string[] = [];
const histograms: string[] = [];
const started = Date.now();
for (const spot of spots) {
  const samples: (PeelSample | undefined)[] = [];
  let lipLaunches = 0;
  let breaking = 0;
  let seconds = 0;
  for (let seed = 1; seed <= seedCount; seed += 1) {
    const run = measureRideability({
      spot,
      seed,
      significantHeight: settings.significantHeight,
      peakPeriod: settings.peakPeriod,
      directionDegrees: settings.directionDegrees,
      spreading: spreadingFor(settings.spread),
      tide: settings.tide,
      windSpeed: settings.windSpeed,
    }, { periods });
    samples.push(...run.samples);
    lipLaunches += run.lipLaunches;
    breaking += run.breakingFraction / seedCount;
    seconds += run.simulatedSeconds;
    console.error(`${spot} seed ${seed}: ${run.stats.waves}/${run.stats.samples} waves, ${((Date.now() - started) / 1000).toFixed(0)} s elapsed`);
  }
  const stats = rideability(samples);
  const median = Number.isNaN(stats.medianAngle) ? '—' : `${stats.medianAngle.toFixed(0)}°`;
  rows.push(`| ${spot} | ${stats.waves} / ${stats.samples} | ${percent(stats.closeout)} | ${percent(stats.mixed)} | ${percent(stats.makeable.professional)} | ${percent(stats.makeable.advanced)} | ${percent(stats.makeable.intermediate)} | ${percent(stats.makeable.beginner)} | ${median} | ${percent(breaking)} | ${(lipLaunches / (seconds / 60)).toFixed(0)} |`);
  histograms.push(`| ${spot} | ${stats.histogram.join(' | ')} |`);
}

const report = `# Rideability report · stage 1 solver

Generated by \`npm run report:rideability -- ${process.argv.slice(2).join(' ')}\` on ${new Date().toISOString().slice(0, 10)} (plan §4 item 11; reported, not asserted).

**Conditions.** ${custom ? 'Custom' : 'The Wave Lab defaults'}: Hs ${settings.significantHeight} m, Tp ${settings.peakPeriod} s, ${settings.directionDegrees}° from shore-normal, spreading s ${spreadingFor(settings.spread).toFixed(0)}, tide ${settings.tide} m, calm wind. Game resolution: 1 m surf-zone cells and a 160 m along-shore window. Each spot runs seeds 1–${seedCount} for ${periods} peak periods after the spin-up. The peel is sampled once per period from the onsets of that period.

**Reading it.** A wave is makeable by a skill level when its peel angle reaches that level's minimum (Hutt, Black & Mead 2001: professional ${PEEL_SKILL_MINIMUM.professional}°, advanced ${PEEL_SKILL_MINIMUM.advanced}°, intermediate ${PEEL_SKILL_MINIMUM.intermediate}°, beginner ${PEEL_SKILL_MINIMUM.beginner}°). The shares are cumulative: every beginner wave is also a professional wave. A close-out peels at under ${PEEL_SKILL_MINIMUM.professional}°. "Mixed" means the onset fit found several peaks at once, so no single angle applies. Shares are of the sampled periods that had a break.

| Spot | Waves / periods | Close-out | Mixed | Pro | Advanced | Intermediate | Beginner | Median α | Breaking | Lip throws / min |
|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
${rows.join('\n')}

Peel angles of clean (non-mixed) waves, per 10° bin:

| Spot | 0–10° | 10–20° | 20–30° | 30–40° | 40–50° | 50–60° | 60–70° | 70–80° | 80–90° |
|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|
${histograms.join('\n')}

**Known limits.**
- Ride-time distributions need a rider in the physical mode (P4), so they are not reported yet.
- The stage 1 solver has no dispersion, so waves break early and as bores. This is a known bias (plan §1.7) that the stage 2 Boussinesq solver removes.
- On the reef, the shelf edge lies inside the tank's offshore boundary blend (z −270 to −190). The measured break is therefore the bore crossing the flat shelf, not the plunge on the edge.
- The peel is measured over the along-shore window only, with 10 % of the columns at each open edge left out.

Run time: ${((Date.now() - started) / 60000).toFixed(1)} min.
`;
writeFileSync(output, report);
console.error(`wrote ${output}`);
