/**
 * The stance map (the riding-body plan, step 2): each stance's targets with
 * their sources, and today's drawn body measured against them. Every stance is
 * simulated by the real rider for Regular and Goofy, posed by the rig alone on
 * the four surfers' own skeletons (read from their GLBs), and measured by the
 * stance gauge. Writes docs/research/stance-map.md.
 *
 *   npm run report:stances
 *   npm run report:stances -- --out /tmp/stances.md
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { Vector3 } from 'three';
import { stanceState } from '../src/dev/ridingPoses';
import { MEASURE_LABEL, MEASURE_OWNER, compareStance, formatMeasure, stanceSection, type StanceReading, type StanceRow } from '../src/dev/stanceReport';
import { readGlbSkeleton } from '../src/scene/rig/glbSkeleton';
import { HumanoidRig } from '../src/scene/rig/HumanoidRig';
import { createRiderVisualState } from '../src/scene/rig/riderVisualState';
import { StanceGauge, type StanceMeasure } from '../src/scene/rig/stanceGauge';
import { APPROVED, CONFIDENCE_CAP, PROVENANCE, SOURCES, STANCES, type SourceId } from '../src/scene/rig/stanceMap';

const option = (name: string): string | undefined => {
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : undefined;
};
const output = option('out') ?? 'docs/research/stance-map.md';
const started = Date.now();

const SURFERS: { id: string; height: number; sex: string }[] = JSON.parse(readFileSync('public/assets/surfers/surfers.json', 'utf8')).surfers;
const glbs = new Map(SURFERS.map(({ id }) => {
  const bytes = readFileSync(`public/assets/surfers/${id}.glb`);
  return [id, bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength)] as const;
}));
const at = new Vector3(0, 0.03, 0);

const sections: string[] = [];
const outs: { stance: string; row: StanceRow }[] = [];
for (const stance of STANCES) {
  const readings: StanceReading[] = [];
  for (const side of ['regular', 'goofy'] as const) {
    const { state, reached } = stanceState(stance.id, side, at, createRiderVisualState());
    for (const surfer of SURFERS) {
      if (!reached) {
        readings.push({ surfer: surfer.id, stance: side, reached });
        continue;
      }
      // A fresh skeleton at rest for each reading: the gauge takes its facings from the rest pose.
      const { bones } = readGlbSkeleton(glbs.get(surfer.id)!);
      const gauge = new StanceGauge(bones);
      new HumanoidRig(bones).solve(state);
      readings.push({ surfer: surfer.id, stance: side, reached, angles: gauge.measure(state, side) });
    }
  }
  const comparison = compareStance(stance, readings);
  for (const row of comparison.rows) if (row.status === 'out') outs.push({ stance: stance.name, row });
  sections.push(stanceSection(stance, comparison));
}

const sourceRows = (Object.entries(SOURCES) as [SourceId, (typeof SOURCES)[SourceId]][])
  .sort(([, a], [, b]) => PROVENANCE.indexOf(a.kind) - PROVENANCE.indexOf(b.kind))
  .map(([id, source]) => {
    const link = source.url ? `[${source.cite}](${source.url})${source.also ? `, [also](${source.also})` : ''}` : `${source.cite} — ${source.held}`;
    return `| ${source.short}${APPROVED.includes(id) ? ` (#${APPROVED.indexOf(id) + 1})` : ''} | ${source.kind} | ${link} | ${source.gives} |`;
  });

const gapList = (owner: 3 | 6) => {
  const rows = outs.filter(({ row }) => MEASURE_OWNER[row.measure] === owner);
  if (!rows.length) return ['- none'];
  return rows.map(({ stance, row }) => `- ${stance}: ${MEASURE_LABEL[row.measure].toLowerCase()} out by ${row.miss > 0 ? '+' : ''}${formatMeasure(row.measure, row.miss)} (target ${formatMeasure(row.measure, row.target.min)} to ${formatMeasure(row.measure, row.target.max)}, ${row.target.confidence})`);
};

const measured = STANCES.reduce((sum, stance) => sum + Object.keys(stance.targets).length, 0);
const document = `# The stance map

Generated by \`npm run report:stances\` on ${new Date().toISOString().slice(0, 10)} (${((Date.now() - started) / 1000).toFixed(0)} s). The riding-body plan, step 2 (\`docs/superpowers/plans/2026-09-28-stance-map.md\`); the data is \`src/scene/rig/stanceMap.ts\`.

${STANCES.length} stances, ${measured} targets. Each target is a range of a joint angle (or the hand's height, the stance's width, the weight's place), with its sources and a confidence. Beside it, today's drawn body: every stance simulated by the real rider (\`src/dev/ridingPoses.ts\`), posed by the rig alone on each of the four surfers' own skeletons, Regular and Goofy, and measured by the stance gauge (\`src/scene/rig/stanceGauge.ts\`). "Today" is the mean over the four surfers, with their spread; a target is met when the mean of all eight readings is inside it.

## How to read it

- **Provenance (the user's rule, Q20):** peer-reviewed measurements first, then the thesis (de Sousa 2022), then coaching cues, then the approved videos as read from their frames. A target claims at most ${PROVENANCE.map((kind) => `${kind} → ${CONFIDENCE_CAP[kind]}`).join(', ')}. A coaching cue turned into numbers, or a direction read as a range, is marked in its note.
- **Gaps:** where no source reaches a measure there is no target. It is listed under the stance, never filled from the drawn body.
- **Who owns a gap:** the drawn pose (step 3) owns the rig's own choices and how it maps the physics' crouch onto the legs; the physics' posture (step 6) owns what its seven points set (the trunk, the lean, the hands' height, the feet, the weight). The physics changes only where the map proves it wrong.
- **Pictures:** cited by link and timestamp below; nothing is copied into the repo. The surfer sheet's \`?stances\` view draws each stance beside a reference figure built from these targets.

## Measures

On the board: x across, y the deck's normal, z the nose. Regular faces −x (the toes' rail) with the left foot forward; Goofy faces +x, the right foot forward. The lead arm is the front foot's side.

- **Knees, hips, elbows:** included angles, 180° straight. The hip is between the trunk (the spine's base to the neck) and the thigh, so it includes the lower back.
- **Ankles:** the shin's tilt from the deck's normal (the ankle's flexion with the foot flat).
- **Trunk:** its tilt from the deck's normal, toward the toes and toward the nose. **Lean:** the feet's middle to the neck, from the world's vertical toward the toes.
- **Twists and head yaw:** where the chest, the pelvis and the head face, on the deck: 0° toward the toes, + toward the nose. **Head pitch:** below the deck's plane.
- **Arms:** the upper arm from the trunk's down: 0° hanging, 90° out, 180° overhead.
- **Lower hand:** the lower wrist's height above the board's centre (about the waterline). **Stance width:** the ankles apart along the stringer. **Weight:** the hips' centre between the rear ankle (0) and the front ankle (1), standing in for the share of weight on the front foot.

## Sources

| Source | Kind | Reference | What it gives the map |
|---|---|---|---|
${sourceRows.join('\n')}

(#n: the reference's number in the set the user approved, Q19.)

## Where today's drawn body misses the map

**Step 3, the drawn pose:**

${gapList(3).join('\n')}

**Step 6, the physics' posture:**

${gapList(6).join('\n')}

## The stances

${sections.join('\n')}`;

writeFileSync(output, document);
console.log(`wrote ${output}: ${STANCES.length} stances, ${measured} targets, ${outs.length} out of range (${((Date.now() - started) / 1000).toFixed(0)} s)`);
