/**
 * Tube report (plan P7): runs each spot's physical surf zone and reports how
 * its breaks go (plunging jets, spilling rollers), the tubes the jets draw
 * (each landed lip parcel measured in the frame of the crest it left, against
 * the measured width-to-length range 0.25-1), the peel, and the step time.
 * Writes docs/research/tube-report.md.
 *
 *   npm run report:tubes -- --seeds 2 --periods 12
 *   npm run report:tubes -- --practice --spots point,reef
 */
import { writeFileSync } from 'node:fs';
import { DEFAULT_PHYSICAL_SETTINGS, swellFor } from '../src/game/PhysicalMode';
import type { SpotName } from '../src/wave/Bathymetry';
import { JET_SPEED_RATIO } from '../src/wave/CrestKinematics';
import { JET_RELEASE_TIME } from '../src/wave/PlungingLip';
import { rideability, type PeelSample } from '../src/wave/Rideability';
import { SurfZoneSimulation } from '../src/wave/SurfZoneSimulation';
import { measureTube } from '../src/wave/TubeShape';

const option = (name: string): string | undefined => {
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : undefined;
};
const argument = (name: string, fallback: number): number => Number(option(name) ?? fallback);
const seedCount = argument('seeds', 2);
const periods = argument('periods', 12);
const practice = process.argv.includes('--practice');
const spots = (option('spots')?.split(',') ?? ['beach', 'point', 'reef', 'canyon']) as SpotName[];
const output = option('out') ?? 'docs/research/tube-report.md';
const settings = practice ? { ...DEFAULT_PHYSICAL_SETTINGS, source: 'practice' as const } : DEFAULT_PHYSICAL_SETTINGS;
const swell = swellFor(settings);
const STEP = 1 / 30;

const fixed = (value: number, digits = 2) => (Number.isFinite(value) ? value.toFixed(digits) : '—');
const quantile = (values: number[], q: number) => {
  if (!values.length) return Number.NaN;
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.min(sorted.length - 1, Math.floor(q * sorted.length))];
};

const rows: string[] = [];
const started = Date.now();
for (const spot of spots) {
  let jets = 0;
  let rollers = 0;
  let stepMs = 0;
  let steps = 0;
  const lengths: number[] = [];
  const ratios: number[] = [];
  const samples: (PeelSample | undefined)[] = [];
  for (let seed = 1; seed <= seedCount; seed += 1) {
    const simulation = new SurfZoneSimulation({
      spot, seed, significantHeight: swell.significantHeight, peakPeriod: swell.peakPeriod,
      directionDegrees: swell.directionDegrees ?? settings.directionDegrees, spreading: swell.spreading, bandwidth: swell.bandwidth,
      tide: settings.tide, windSpeed: settings.windSpeed,
    });
    simulation.lip.onLand = (x, z, _volume, _vx, _vy, _vz, flight) => {
      if (!flight) return;
      const tube = measureTube(flight.launch, { x, z }, flight.y, flight.crestSpeed * flight.age);
      lengths.push(tube.length);
      if (tube.length > 0) ratios.push(tube.widthRatio);
    };
    const perPeriod = Math.round(swell.peakPeriod / STEP);
    for (let period = 0; period < periods; period += 1) {
      for (let index = 0; index < perPeriod; index += 1) {
        simulation.step(STEP);
        stepMs += simulation.lastStepMs;
        steps += 1;
      }
      const estimate = simulation.peelEstimate();
      samples.push(estimate && { angleDegrees: estimate.angleDegrees, fit: estimate.fit });
    }
    jets += simulation.lipJets;
    rollers += simulation.lipRollers;
    console.error(`${spot} seed ${seed}: ${simulation.lipJets} jets, ${simulation.lipRollers} rollers, ${((Date.now() - started) / 1000).toFixed(0)} s elapsed`);
  }
  const stats = rideability(samples);
  const inRange = ratios.filter((ratio) => ratio >= 0.25 && ratio <= 1).length;
  rows.push(`| ${spot} | ${jets} | ${rollers} | ${lengths.length} | ${lengths.length ? Math.round((100 * ratios.length) / lengths.length) : 0} % | ${fixed(quantile(lengths, 0.5))} | ${fixed(quantile(lengths, 0.9))} | ${fixed(quantile(ratios, 0.5))} | ${ratios.length ? Math.round((100 * inRange) / ratios.length) : 0} % | ${Math.round(stats.closeout * 100)} % | ${Math.round(stats.mixed * 100)} % | ${Number.isFinite(stats.medianAngle) ? Math.round(stats.medianAngle) + '°' : '—'} | ${fixed(stepMs / Math.max(1, steps), 1)} |`);
}

const report = `# Tube report · physical surf zone

Generated by \`npm run report:tubes -- ${process.argv.slice(2).join(' ')}\` on ${new Date().toISOString().slice(0, 10)} (plan P7; reported, not asserted).

**Conditions.** ${practice ? 'Practice groundswell' : 'The Wave Lab defaults'}: Hs ${swell.significantHeight} m, Tp ${swell.peakPeriod} s, spreading s ${Math.round(swell.spreading)}. Stage 2 (Boussinesq) on the CPU. ${seedCount === 1 ? 'Seed 1' : `Seeds 1–${seedCount}`}, ${periods} peak periods each.

**How tubes are measured.** A break is a plunging jet where the local Iribarren number under its crest is 0.4–2, and a spilling roller below 0.4. A jet leaves at the crest's own speed, measured from the surface's motion on its front face (JET_SPEED_RATIO ${JET_SPEED_RATIO}, provisional), over ${JET_RELEASE_TIME} s (provisional). Each landed lip parcel is measured in the frame of the crest it left: its tube length is how far ahead of the advancing crest it landed, its height the drop to the surface it landed on. A lip the wave overruns has no tube. The measured range is width-to-length 0.25–1 (Feddersen et al. 2023 at Surf Ranch; passyworld up to round).

| Spot | Jets | Rollers | Landed parcels | With a tube | Median tube length, m | 90th percentile, m | Median width / length | Within 0.25–1 | Close-out | Mixed | Median peel | Step, ms |
|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
${rows.join('\n')}

**Reading it.** Until measured jet kinematics are in (the jet's speed relative to the crest at overturning, where it leaves the face, and its thickness), a jet thrown at the crest's own speed lands on the face just ahead of the crest: tubes are centimetres long, if any. The P7 plan records this finding.
`;

writeFileSync(output, report);
console.error(`wrote ${output}`);
