"""Independent read-only audit of successful physical-mouth native capture."""
from pathlib import Path
import hashlib,json,math,struct
P=Path('/private/tmp/tube-bounded-c-parallel-physics-mouth-native-20261004');OUT=Path(__file__).parent
def read(p):return json.loads(Path(p).read_text())
def pin(p):
 b=Path(p).read_bytes();return {'file':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def verify(p):return all(pin(p['file'])[k]==p[k] for k in ['bytes','sha256'])
report=read(P/'candidate-first/report.json');owner=read(P/'candidate-first-owner.json');seal=read(P/'seal.json');build=read(P/'root-complete-build-result.json');arm=seal['arms']['candidate'];obs=report['observations'];valid=[q for q in obs if not q['missing']];sel=report['selection'];video=report['video'];launcher=read(P/'candidate-first/launcher.json');last=obs[-1]
checks=[]
def ck(name,value,scope=None):checks.append({'name':name,'passed':bool(value),**({'scope':scope} if scope else {})})
groups={'source':arm['sourcePins'],'helpers':seal['helperPins'],'assets':arm['assetPins'],
 'buildSource':build['sourcePins'],'builtAssets':build['builtAssetPins'],'frozenAssets':build['frozenAssetPins'],
 'buildReferences':[arm['rootBuildManifest'],build['rootOriginalBuildResult'],build['rootPartialBuildResult'],build['priorStaticAssetsSeal']],
 'sealedPriorReferences':[seal[k] for k in ['priorAirSeal','priorFullsheetSeal','priorParallelSeal','priorMouthSeal','physicalSourceReadiness']]+list(seal['priorFailedParallel'].values())+list(seal['priorFailedMouth'].values()),
 'staticCopies':[p[k] for p in build['staticComposition']['references'] for k in ['source','frozenCopy']]+[p[k] for p in build['staticComposition']['overlap'] for k in ['source','sameBuiltAsset']],
 'servedAssets':[{'file':str(Path(owner['dist'])/relative),**p} for relative,p in owner['served'].items()],
 'captureArtifacts':[{'file':str(P/'candidate-first'/p['file']),**{k:v for k,v in p.items() if k!='file'}} for p in report['artifacts']]}
partial=read(build['rootPartialBuildResult']['file']);groups['preservedPartialAssets']=partial['assetPins']
pins={name:{'count':len(ps),'allMatched':all(verify(p) for p in ps),'failures':[p['file'] for p in ps if not verify(p)]} for name,ps in groups.items()}
for k,v in pins.items():ck('pins:'+k,v['allMatched'])
ck('seal reference and arm',owner['sealSha256']==pin(P/'seal.json')['sha256'] and report['seal']==arm and arm['sourcePins']==build['sourcePins'] and arm['assetPins']==build['frozenAssetPins'])
ck('successful frozen owner retained',owner['complete'] is True and owner['firstFailure'] is None and owner['exitCode']==0 and owner['sourceBuildHelpersPostUnchanged'] is True)
ck('successful native and build',report['complete'] is True and report['firstFailure'] is None and build['terminal'] is True and build['exitCode']==0 and build['sourceUnchangedAfterBuild'] is True)
ck('recorded resource closure',owner['independentClosureValid'] is True and owner['protectedPortsPreserved'] is True and owner['protectedStatesInitially']==owner['protectedStatesFinally'] and owner['remainingOwnedPids']==[] and all(owner['closedPorts'].values()) and report['chromeClosed'] is True and launcher['ownedChromeClosed'] is True and launcher['exit']['code']==0,'Existing frozen receipts only; no new resource probe.')
ck('no browser errors',report['browserErrors']==[])
ck('bounds and artifacts',3<=len(report['checkpoints'])<=4 and {'initial','initial-exterior','terminal'}<={c['label'] for c in report['checkpoints']} and report['pngBytes']<=48*1024*1024 and video['bytes']<=16*1024*1024 and (P/'candidate-first/report.json').stat().st_size<=32*1024*1024 and report['detectorMilliseconds']<=20000 and sel['step']<=300 and video['physicsAdvances']<=240)
req=report['videoRequests'];ck('ordered ordinary steps and requests',2<=len(req)<=241 and len(req)==video['requestFrameCount']==len(obs) and video['physicsAdvances']==len(obs)-1 and [q['movingStep'] for q in obs]==list(range(len(obs))) and all(abs(obs[i]['seaTime']-obs[i-1]['seaTime']-1/60)<1e-7 for i in range(1,len(obs))))
ck('request camera and clock ties',all(q['request']==i+1 and q['step']==o['step'] and q['seaTime']==o['seaTime'] and q['cameraPosition']==o['camera']['position'] and q['cameraQuaternion']==o['camera']['quaternion'] for i,(q,o) in enumerate(zip(req,obs))))
ck('no FPS playback or encoded-frame acceptance',report['fpsClaim'] is False and video['physicalPlaybackRateClaim'] is False and video['encodedFrameCountClaim'] is False and video['tracksStopped'] is True)
ck('fixed Eulerian selection',all(q['locked']==sel['locked'] and q['locked']['stationIdentity']=='fixed-Eulerian-solver-column-crest-station' and q['locked']['materialTrajectoryClaim'] is False and q['retirementClaim'] is False and isinstance(q['currentFront'],int) and len(q['rawFrontRecords'])==q['counts']['front'] for q in obs))
ck('current draw epoch',all(e['drawnWaterTimeMatchesCurrentSnapshot'] is True and e['snapshotIdentityUnchanged'] is True and e['physicsClockUnchanged'] is True and e['supportedOrder']==['water.update','mode.drawBarrel'] and abs(e['seaTime']-q['seaTime'])<1e-7 and e['drawnRevisionIsCurrentStatus'] is True and e['drawnFrontIsCurrentBuffer'] is True and e['drawnCount']==q['counts']['front'] and e['drawnSurfaceRevision']==e['surfaceRevisionAfter'] for q in obs for e in [q['drawEpoch']]))
ck('exact render words/actors/epoch',all(all(v is True for v in q['renderEvidence'].values()) for q in obs[1:]) and all(all(v is True for v in c['evidence'].values()) and c['normalMeshOpacityAndVisibility'] is True for c in report['checkpoints']),'Frozen byte-comparison helper and recorded runtime flags; whole arrays are not persisted for offline reconstruction.')
exports={e['step']:e for q in obs for e in q['publicExportEvidence']};flags=['snapshotClockStatusWordsUnchanged','normalActorPoseAndCameraUnchanged','surfaceWordsAndEpochUnchanged','drawGenerationUnchanged','exactLoftWordsUnchanged']
ck('exact public export words gates',all(all(e[k] is True for k in flags) and e['solverArraysDecodedOrRetained'] is False and abs(e['exportedSeaTime']-e['seaTime'])<1e-7 for e in exports.values()))
ck('initial identity runtime gates',all(q['initialPublicPointIdentity']['qualified'] is True and all(v is True for v in q['initialPublicPointIdentity']['gates'].values()) and len(q['initialPublicPointIdentity']['pointIDs'])==2 for q in obs),'Global active-ID uniqueness is a runtime flag; retained matching two-point parity is recomputed below.')
ck('ray diagnostics',all(d['rayInvalidIntervals']==0 and (d['joinedRowPairs']==0 or d['rayMinAdvance']>0 and d['rayMaxBlend']==1) for q in obs for d in [q['rayDiagnostics']]) and all(q['ray']==[0,1] for q in valid))
ck('actual loft station and opening camera',all(q['rawMappingCorroboration']['usedToLocateLoftRows'] is False and q['loftStation']['bracket'] is not None and q['retargeted'] is False and q['visibilityProven'] is False and (not q['openingPresent'] or q['cameraColumns']['eye']['strictSameFrontAirBandContainsCameraHeight'] is True) for q in valid))
ck('join loss retains failure and held camera',report['stop']['reason']=='loft-join-absent' and last['missing'] is True and last['stopReason']=='loft-join-absent' and last['retirementClaim'] is False and len(last['allFrontRowsOnLoss'])==last['counts']['slices'] and last['cameraHeldAtLastValidPose'] is True and last['camera']==obs[-2]['camera'])
initial=sel['initialPublicPointIdentity']['points'];fp=['x','footHeight','footDepth','throwZ','jetPace','jetBase','jetAt','jetUntil']
def f32(x):return struct.unpack('f',struct.pack('f',x))[0]
def pointParity(identity,raw):return len(identity['points'])==2 and identity['matchCounts']==[1,1] and all(p['id']==initial[i]['id'] and p['column']==initial[i]['column'] and all(p[k]==initial[i][k] for k in fp) and all(f32(p[k])==raw[i][k] for k in ['x','z','front','sigma','tau','footHeight','footDepth','throwZ']) and 0<=p['tau']<p['jetUntil'] and f32(p['jetPace'])==raw[i]['pace'] for i,p in enumerate(identity['points']))
ck('retained initial identity parity',pointParity(sel['initialPublicPointIdentity'],sel['mapping']['rawRows']))
events=[]
for q in obs:
 e=q['lineageDecision']
 if not e.get('componentLineageEvent'):continue
 cs=[c for c in e['testedCandidates'] if c['qualified']];c=cs[0]
 ck('lineage event '+str(q['step']),len(cs)==e['qualifiedCount']==1 and c['front']==q['currentFront'] and all(v is True for v in c['gates'].values()) and e['materialTrajectoryClaim'] is False and e['DTEqualityRequired'] is False and e['provenOrderedInternalPointIDs']==[p['id'] for p in initial] and pointParity(c['publicPointIdentity'],c['afterRawColumns']) and all(a['passesMonotone'] is True for a in c['ages']))
 events.append({'step':q['step'],'before':e['beforeFront'],'after':e['afterFront'],'IDs':e['provenOrderedInternalPointIDs'],'testedCandidates':len(e['testedCandidates']),'gates':c['gates'],'ageDiagnostics':c['ages'],'crestZDiagnostics':c['crestZMotion']})
mouths=[q for q in valid if isinstance(q.get('mouth'),dict)]
mouthProofs=[]
for q in mouths:
 m=q['mouth'];ats=m['attempts'];iv=m['interval'];first=next((a for a in ats if a['qualified']),None)
 okay=(len(ats)==m['maximumColumnQueries']==24 and m['immutableYoungerSign']==q['locked']['youngerSign'] and iv['closestBoundaryFirst'] is True and iv['strictlyYoungerward'] is True and m['candidate']==first and all(a['sample']==i and a['intervalFraction']==(i+.5)/24 and abs(a['rowCoordinate']-(m['boundaryRow']-m['immutableYoungerSign']*iv['directedLength']*a['intervalFraction']))<1e-10 and a['directedProgress']>0 for i,a in enumerate(ats)))
 if first:
  c=first['covering'][0];okay=okay and first['sameEyeSheetComponent'] is True and len(first['covering'])==1 and c['component']['front']==q['currentFront'] and c['component']['localId']==q['indexedColumn'][0]['component']['localId'] and len(c['crossings'])==3 and c['strictlyOrdered'] is True and first['point']==[first['x'],(c['crossings'][0]+c['crossings'][1])/2,first['z']]
 okay=okay and m['externalEntranceClaim'] is False and m['continuousAirCorridorClaim'] is False and m['bodyPassageClaim'] is False
 mouthProofs.append({'step':q['step'],'passed':okay,'qualifiedSamples':sum(a['qualified'] for a in ats),'boundary':m['boundaryReason'],'candidateSample':first['sample'] if first else None,'candidateRows':first['rows'] if first else None,'candidateRowProgress':first['directedProgress'] if first else None,'eyeToCandidateDistance':math.dist(q['eye'],first['point']) if first else None,'directedIntervalRowLength':iv['directedLength'],'failure':m['failure'],'targetUsed':m['targetUsed'],'clearInternalSegment':m['clearNearMouthSightline'],'eyeBelowSurface':m['eyeBelowSurface'],'targetBelowSurface':m['targetBelowSurface'],'exteriorBelowSurface':m['exterior']['belowSurface'] if m['exterior'] else None,'exteriorHit':m['exterior']['fullSightline']['firstHit'] if m['exterior'] else None,'shorewardHit':m['shorewardContinuation']['fullSightline']['firstHit'] if m['shorewardContinuation'] else None})
ck('mouth full-interval discrete policy',all(m['passed'] for m in mouthProofs),'24 uniform interior stations span the interval; no continuous corridor or whole-boundary coverage certificate.')
ck('mouth target/clear segment records',all(m['failure'] is None and m['targetUsed'] is True and m['clearNearMouthSightline'] is True and m['fullSightline']['indexedLoftOccluded'] is False and m['fullSightline']['firstHit'] is None and m['target']==m['candidate']['point']==q['target'] and m['localHeadingRetainedOnFailure'] is False for q in mouths for m in [q['mouth']]))
ck('single declared exterior pose and obstructed failure retained',all(e['anchorPolicy']=='current-strict-air-mouth-candidate' and e['mouthCandidateAvailable'] is True and e['anchorPoint']==q['mouth']['candidate']['point']==e['target'] and e['poseRetries']==0 and e['externalEntranceClaim'] is False and e['fullSightline']['indexedLoftOccluded'] is True and e['fullSightline']['firstHit'] is not None for q in mouths for e in [q['mouth']['exterior']]))
ck('shoreward continuation obstruction recorded',all(m['shorewardContinuation']['fullSightline']['indexedLoftOccluded'] is True and m['shorewardContinuation']['fullSightline']['firstHit'] is not None and m['shorewardContinuation']['exteriorEntranceClaim'] is False for q in mouths for m in [q['mouth']]))
ck('mouth runs only while local air exists',all((isinstance(q.get('mouth'),dict))==q['openingPresent'] for q in valid))
ck('scope limits remain explicit',report['bodyEntryClaim'] is False and report['physicalGeometryEqualityClaim'] is False and report['nativeMovingAppearanceProven'] is False and report['newPhysicalCandidateNotCameraOnlyEquality'] is True)
def angle(a,b):return math.degrees(math.acos(max(-1,min(1,sum(x*y for x,y in zip(a,b))/(math.hypot(*a)*math.hypot(*b))))))
deltas=[]
for a,b in zip(valid,valid[1:]):deltas.append({'step':b['step'],'crestDistance':math.dist(a['crest'],b['crest']),'crestZDelta':b['crest'][2]-a['crest'][2],'eyeDistance':math.dist(a['eye'],b['eye']),'tangentAngle':angle(a['tangent'],b['tangent']),'airRemains':a['openingPresent'] and b['openingPresent']})
for e in events:e['poseDelta']=next(d for d in deltas if d['step']==e['step'])
def station(q):
 b=q['loftStation']['bracket'];rows={r['row']:r for r in q['lockedFrontRows']};a=rows[b['a']];z=rows[b['b']];t=b['t'];keys=['row','sliceSigma','sliceTau','slicePhase','sliceFade','sliceWeight','sliceJoined','crest','cap','toe']
 return {'bracket':{k:b[k] for k in ['a','b','t']},'rows':[{k:r[k] for k in keys} for r in [a,z]],'landmarks':{name:[a[name][i]+t*(z[name][i]-a[name][i]) for i in range(3)] for name in ['crest','cap','toe']},'weight':a['sliceWeight']+t*(z['sliceWeight']-a['sliceWeight']),'fade':a['sliceFade']+t*(z['sliceFade']-a['sliceFade'])}
st={str(i):station(obs[i]) for i in [63,64]};ld={name:{'delta':[b-a for a,b in zip(st['63']['landmarks'][name],st['64']['landmarks'][name])],'distance':math.dist(st['63']['landmarks'][name],st['64']['landmarks'][name])} for name in ['crest','cap','toe']}
geometry={'locked':sel['locked'],'initialExportedPoints':initial,'publicExportEpochs':sorted(exports),'lineageEvents':events,'openSteps':[q['step'] for q in valid if q['openingPresent']],'lostAirSteps':[q['step'] for q in valid if not q['openingPresent']],'firstPhase2':report['firstObservedPhase2'],'heights':{str(i):obs[i].get('openingHeight') for i in [0,30,47,48,54,55]},'rayMinAdvanceRange':[min(q['rayDiagnostics']['rayMinAdvance'] for q in obs),max(q['rayDiagnostics']['rayMinAdvance'] for q in obs)],'maxWhileAirPose':{k:max([d for d in deltas if d['airRemains']],key=lambda d:d[k]) for k in ['crestDistance','eyeDistance','tangentAngle']},'maxAllValidPose':{k:max(deltas,key=lambda d:d[k]) for k in ['crestDistance','eyeDistance','tangentAngle']},'station63to64':st,'landmark63to64':ld,'raw63':obs[63]['mapping']['rawRows'],'raw64':obs[64]['mapping']['rawRows'],'finalRawBracket':last['mapping']['rawRows'],'finalRawRange':last['mapping']['range'],'finalJoinedRange':[last['lockedFrontRows'][0]['crest'][0],last['lockedFrontRows'][-1]['crest'][0]],'stationBeforeFinalFirstRow':last['lockedFrontRows'][0]['crest'][0]-sel['locked']['stationX'],'finalJoinedRows':len(last['lockedFrontRows']),'finalJoinedPairs':last['loftStation']['joinedPairs'],'poseDeltas':deltas}
mouthSummary={'epochs':len(mouths),'totalDiscreteColumnQueries':24*len(mouths),'allInternalSegmentsClear':all(m['clearInternalSegment'] for m in mouthProofs),'allExteriorSegmentsObstructed':all(m['exteriorHit'] is not None for m in mouthProofs),'allShorewardSegmentsObstructed':all(m['shorewardHit'] is not None for m in mouthProofs),'qualifiedSampleRange':[min(m['qualifiedSamples'] for m in mouthProofs),max(m['qualifiedSamples'] for m in mouthProofs)],'eyeCandidateDistanceRange':[min(m['eyeToCandidateDistance'] for m in mouthProofs),max(m['eyeToCandidateDistance'] for m in mouthProofs)],'fullIntervalRowLengthRange':[min(m['directedIntervalRowLength'] for m in mouthProofs),max(m['directedIntervalRowLength'] for m in mouthProofs)],'candidateProgressRowsRange':[min(m['candidateRowProgress'] for m in mouthProofs),max(m['candidateRowProgress'] for m in mouthProofs)],'initialContourWidth':mouths[0]['mouth']['exterior']['initialContourWidth'],'initialCandidate':mouths[0]['mouth']['candidate'],'initialExterior':mouths[0]['mouth']['exterior'],'initialShoreward':mouths[0]['mouth']['shorewardContinuation'],'records':mouthProofs}
result={'schema':'bounded-C-parallel-physics-mouth-native-independent-analysis/v1','readOnly':True,'successfulOwnerUnmodified':True,'earlierRejectedReceiptsUnmodified':True,'allIndependentChecksPassed':all(c['passed'] for c in checks),'checks':checks,'pins':pins,'inputPins':[pin(P/f) for f in ['seal.json','candidate-first-owner.json','candidate-first/report.json','candidate-first/launcher.json','run.py','mouth-tools.mjs','moving-shape.mjs','root-complete-build-result.json']], 'runtimeCouplingPins':[pin(Path(arm['source'])/f) for f in ['src/wave/barrel/SweptCrash.ts','src/wave/barrel/crashCurve.ts']],'outputPins':groups['captureArtifacts'],'owner':{k:owner[k] for k in ['complete','firstFailure','exitCode','sealSha256','sourceBuildHelpersPostUnchanged','independentClosureValid','protectedPortsPreserved','protectedStatesInitially','protectedStatesFinally','closedPorts','remainingOwnedPids','elapsedSeconds']},'native':{k:report[k] for k in ['complete','firstFailure','video','stop','browserErrors','detectorMilliseconds','firstObservedPhase2']},'geometry':geometry,'mouth':mouthSummary,'scope':'No whole entrance, continuous air corridor, body passage, material trajectory, FPS, production adoption or cross-candidate state equality. Recorded helper byte comparisons and geometry evidence cannot establish exact raster appearance alone.'}
(OUT/'analysis.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps({'allChecksPassed':result['allIndependentChecksPassed'],'failedChecks':[c for c in checks if not c['passed']],'checkCount':len(checks),'pins':pins,'geometry':{k:geometry[k] for k in ['firstPhase2','maxAllValidPose','stationBeforeFinalFirstRow','landmark63to64']},'mouthSummary':{k:v for k,v in mouthSummary.items() if k not in ['initialCandidate','initialExterior','initialShoreward','records']}},indent=2))
