"""Arithmetic-only diagnosis of already-failed frozen queries. No new parameter grid."""
from pathlib import Path
import importlib.util,json,math,collections
W=Path('/private/tmp/tube-bounded-c-precision-v2-20261004');B=Path('/private/tmp/tube-bounded-c-profile-20261004')
sp=importlib.util.spec_from_file_location('frozen',W/'prototype.py');p=importlib.util.module_from_spec(sp);sp.loader.exec_module(p)
sp1=importlib.util.spec_from_file_location('v1',B/'prototype.py');v1=importlib.util.module_from_spec(sp1);sp1.loader.exec_module(v1)
r=json.load(open(W/'precision-report.json'));blocks={a['label']:a for a in r['blocks']};rows=[]
for query in r['rows']:
 if query['valid']:continue
 z=query['params'];raw=blocks[query['block']]['raw'];o=p.ordinary(z);m=query['model'];g=m['formation'];T=m['thickness'];P,rc,last,n=p.roof(o,g,m['seal'],T);V=[p.unit(p.sub(b,a)) for a,b in zip(P,P[1:])];N=[[-a[1],a[0]] for a in V];D=[p.mul(N[0],-1)]+[p.mul(p.add(a,b),-1/(1+p.dot(a,b))) for a,b in zip(N,N[1:])]+[p.mul(N[-1],-1)];Q=[p.add(a,p.mul(d,T)) for a,d in zip(P,D)];qJ=(1-g)*Q[-1][0]+g*(o['A'][0]+.28*o['W']);e=next(i for i in range(28) if Q[i][0]<=qJ<=Q[i+1][0]);J=p.mix(Q[e],Q[e+1],(qJ-Q[e][0])/(Q[e+1][0]-Q[e][0]));vr=V[e];angle=(1-g)*math.atan2(o['d0'][1],o['d0'][0]);slope=math.tan(angle);qC=P[-1][0]-T/2;yC=(1-g)*o['K0'][1]+g*o['T'][1]
 u=p.mul(vr,-1);beta=math.atan2(u[1],u[0])%(2*math.pi);spanU=3*math.pi/2-beta;spanL=math.pi/2+angle;dU=[math.sin(3*math.pi/2)-math.sin(beta),-math.cos(3*math.pi/2)+math.cos(beta)];dL=[math.sin(2*math.pi+angle)+1,-math.cos(2*math.pi+angle)];depth=J[1]-yC-slope*(J[0]-qC);coef=dU[1]+dL[1]-slope*(dU[0]+dL[0]);O=p.add(J,[0,-depth]);cU=[-u[1],u[0]];cV=p.add(dU,[0,-coef]);cL=p.add(cV,[1,0]);bounds={'desired':4*T,'floor':depth/-coef if coef<0 else math.inf,'roof':math.inf,'bulk':math.inf}
 for a,b,v in zip(P,P[1:],V):
  nn=[-v[1],v[0]];a=p.sub(a,p.mul(nn,T/2));b=p.sub(b,p.mul(nn,T/2));bounds['roof']=min(bounds['roof'],p.arc_bound(J,cU,p.mul(cU,-1),spanU,a,b),p.arc_bound(O,cL,[-1,0],spanL,a,b),p.face_bound(J,O,dU,cV,a,b))
 bulk=[p.xy(a) for a in raw if a['point']<=32]
 for a,b in zip(bulk,bulk[1:]):
  a=p.add(a,[0,-T/2]);b=p.add(b,[0,-T/2]);bounds['bulk']=min(bounds['bulk'],p.arc_bound(J,cU,p.mul(cU,-1),spanU,a,b),p.arc_bound(O,cL,[-1,0],spanL,a,b),p.face_bound(J,O,dU,cV,a,b))
 _,old=v1.transform(raw,z);rows.append({'block':query['block'],'sample':query['sample'],'tau':z['tau'],'g':g,'requestedThickness':m['requestedThickness'],'8ULPThicknessFloor':T,'inflationFactor':T/m['requestedThickness'],'nominalLipToFloorFormationDepth':g*.12*o['H'],'nominalDepthOverStoredThickness':g*.12*o['H']/T,'actualAvailableRootDepth':depth,'actualRootDepthOverStoredThickness':depth/T,'rootRadiusBounds':bounds,'minimumRadiusRequired':T/2,'selectedRadius':min(bounds.values()),'rootFloorCoefficient':coef,'sameV1Failures':old['failures'],'v1AlsoFails':bool(old['failures'])})
report={'schema':'bounded-C-precision-v2/causal-formation-obstruction','onlyExisting39FailureQueries':True,'noNewGridOrTuning':True,'rows':rows,'allInheritedV1ResolvedBranchFailures':all(a['v1AlsoFails'] for a in rows),'cause':'The scalar64ULP loop LENGTH gate is not a thickness/root feasibility gate. In early formation, raw nominal cap-to-plane depth is about .12*g*H, while the paired sheet is inflated from B*g² to8ULP. At length gate g*min(W,H)=64ULP, depth can be .12*64ULP=7.68ULP, already less than8ULP sheet before offset/root radius costs. After that depth becomes positive before a half-sheet-radius root fits. Both geometry failures occur in the unchanged resolved v1 branch; v2 only repairs the prior retirement whole-envelope snap.','portBlocked':True,'nextStructuralOption':'In a separate explicit precision formulation, sheet existence must depend on actual paired-sheet/bounded-root representability in addition to loop length. Collapse only unresolvable sheet/void with current roof and common floor/tail authority. Do not silently catch arbitrary domain errors or tune64ULP. A general actual local depth/radius feasibility predicate can select ordinary filled topology; define its connector and switch envelope bound before any new evaluation.','notChanged':'No provider/shared source/native helper edits.'}
(W/'causal-formation-analysis.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'allInheritedV1':report['allInheritedV1ResolvedBranchFailures'],'failureCount':len(rows),'depthOverThicknessRange':[min(a['actualRootDepthOverStoredThickness'] for a in rows),max(a['actualRootDepthOverStoredThickness'] for a in rows)],'inflationFactorRange':[min(a['inflationFactor'] for a in rows),max(a['inflationFactor'] for a in rows)],'examples':rows[:2]},indent=2))
