"""Freeze stable-X helpers after actual root-complete build verification. No seal or resources."""
from pathlib import Path
import ast,hashlib,importlib.util,json,sys
sys.dont_write_bytecode=True
W=Path(__file__).resolve().parent;OLD=Path('/private/tmp/tube-bounded-c-carrier-support-native-20261004')
def pin(p):
 p=Path(p).resolve();b=p.read_bytes();return {'file':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def verify(q):assert pin(q['file'])==q,q['file']
def save(name,j):
 p=W/name;assert not p.exists(),p;p.write_text(json.dumps(j,indent=2)+'\n')
for n in ('helper-pins.json','readiness.json','seal.json'):assert not (W/n).exists(),n
cpu=json.loads((W/'cpu-validation.json').read_text());assert cpu['complete'] and not cpu['resourcesStarted'] and not cpu['portsProbed'] and all(r['exitCode']==0 for r in cpu['commands'])
for p in W.glob('*.py'):ast.parse(p.read_text())
check=json.loads((W/'new-source-contract-checks.json').read_text());assert check['complete'] and check['actualRootBuildVerified'] and not check['awaitingRootBuild']
provenance=json.loads((W/'provenance.json').read_text());assert provenance['sourceContractFinal']
for q in json.loads((OLD/'helper-pins.json').read_text()):verify(q)
for q in provenance['parentHelperInputs']:verify(q)
for k in ('parentReadiness','parentHelperManifest','sourceReadiness','sourcePinsManifest','carrierSourceReadiness','publicHistoryContract','parentSourceContract'):verify(provenance[k])
for k in ('priorFailedMouth','priorFailedParallel'):
 for q in provenance[k].values():verify(q)
spec=importlib.util.spec_from_file_location('stable_X_freeze_owner',W/'run.py');owner=importlib.util.module_from_spec(spec);spec.loader.exec_module(owner)
build=json.loads(owner.BUILD_MANIFEST.read_text());assert owner.verify_complete_build(build,owner.CANDIDATE_DIST)
for q in build['sourcePins']+build['assetPins']:verify(q)
assert check['actualBuildSourcePins']==len(build['sourcePins']) and check['actualBuildAssetPins']==len(build['assetPins'])
provenance['rootBuildAvailable']=True;provenance['rootCompleteBuild']=pin(owner.BUILD_MANIFEST);provenance['frozen']=True;(W/'provenance.json').write_text(json.dumps(provenance,indent=2)+'\n')
parent=json.loads((OLD/'readiness.json').read_text())
local=['run.py','native.mjs','native-owned.mjs','moving-shape.mjs','station-tools.mjs','mouth-tools.mjs','loft-snapshot-tools.mjs','mouth-tools.test.mjs','loft-snapshot-tools.test.mjs','mouth-integration-checks.mjs','mock-checks.mjs','identity-checks.mjs','owner-event-checks.py','owner-mock-checks.py','owner-snapshot-checks.py','helper-types.d.ts','README.md','blueprint.txt','provenance.json','check-source.py','new-source-contract-checks.json','cpu-validation-runner.py','cpu-validation.json','cpu-validation.log','mouth-integration-checks.json','mock-checks.json','identity-checks.json','carrier-event-fixtures.json','carrier-probe-fixtures.json','owner-event-checks.json','owner-mock-checks.json','owner-snapshot-checks.json','snapshot-owner-fixture/loft-initial.json','snapshot-owner-fixture/loft-first-phase2.json','freeze.py']
external=[Path('/private/tmp/tube-directed-entry-20261004/body-witnesses.mjs'),Path('/Users/regina/Desktop/Projects/surfing-game/scripts/browser/cdp.mjs'),Path(check['inheritedGpuExportTest']['file']),Path(check['priorSourceContract']['file']),Path(provenance['sourceReadiness']['file']),Path(provenance['sourcePinsManifest']['file']),Path(provenance['publicHistoryContract']['file']),Path(provenance['carrierSourceReadiness']['file']),OLD/'readiness.json']
helpers=[pin(W/n) for n in local]+[pin(p) for p in external];save('helper-pins.json',helpers)
identity=json.loads((W/'identity-checks.json').read_text());moving=json.loads((W/'mock-checks.json').read_text());snapshot=json.loads((W/'owner-snapshot-checks.json').read_text());events=json.loads((W/'owner-event-checks.json').read_text());owners=json.loads((W/'owner-mock-checks.json').read_text())
ready={k:parent[k] for k in ('priorAirSeal','priorFullsheetSeal','priorParallelSeal','priorMouthSeal','priorPhysicalMouthSeal','priorFailedAgeGate','componentLineagePolicy','cameraPolicy','boundarySampling','exteriorAnchorPolicy','protectedStatesRequiredInitiallyAndFinally','directHistoryProbePolicy','loftSnapshotPolicy','maximumNeutralSelectionSteps','maximumMovingSteps','maximumCandidateColumnQueriesPerMouthObservation','detectorMilliseconds','maximumPNGCount','movieBytes','pngBytes','reportBytes','wholeSeconds','commandSeconds','cleanupSeconds','acceptance')}
ready.update({'schema':'bounded-C-stable-X-native-readiness/v1','complete':True,'frozen':True,'resourcesStarted':False,'portsProbed':False,'buildPerformed':False,'sourceModified':False,'rootOwnsBuildCompositionSealAndNative':True,'rootCompleteBuild':pin(owner.BUILD_MANIFEST),'sourcePins':len(build['sourcePins']),'assets':len(build['assetPins']),'frozenSourceReadinessPins':check['frozenReadinessSourcePins'],'helperPins':helpers,'helperPinsManifest':pin(W/'helper-pins.json'),'sourceContractCheck':pin(W/'new-source-contract-checks.json'),'stableXSourceReadiness':provenance['sourceReadiness'],'sourceReadiness':provenance['sourceReadiness'],'sourcePinsManifest':provenance['sourcePinsManifest'],'carrierSourceReadiness':provenance['carrierSourceReadiness'],'publicHistoryContract':provenance['publicHistoryContract'],'priorCarrierSupportSeal':pin(OLD/'seal.json'),'parentHelperReadiness':pin(OLD/'readiness.json'),'priorFailedParallel':provenance['priorFailedParallel'],'priorFailedMouth':provenance['priorFailedMouth'],'checks':{'initialCPUCommands':22,'focusedDescriptiveDiagnosticFollowups':3,'identityGroups':identity['groupCount'],'movingExportGroups':moving['groupCount'],'ownerSnapshotGroups':snapshot['groupCount'],'ownerProtectedAndBuildGroups':owners['groupCount'],'actualPriorIdentityTransitions':events['actualRecordedIdentityTransitionsPassed'],'actualPriorEventsProveCurrentLeaseSemantics':False,'syntheticCarrierEvents':events['syntheticCarrierEventsPassed'],'syntheticDirectProbeObservations':events['syntheticDirectProbeObservationsPassed'],'syntheticDirectProbeMutationsRejected':events['syntheticDirectProbeMutationsRejected'],'unchangedPublicSourcePairs':len(check['unchangedPublicDrawingExportControlSourcePairs']),'declaredChangedPublicSourcePairs':len(check['changedPublicSourcePairsDeclaredRuntime']),'sourceReadinessAllPinsVerified':True,'rootBuildAllPinsVerified':True,'snapshotToolsTests':6,'indexedMouthGeometryTests':11,'checkJsNoEmit':cpu['checkJsNoEmit'],'PythonAST':True,'JSsyntax':cpu['JSsyntax'],'dryOwnerNoResources':True,'inheritedGpuTestNotRerun':True,'descriptiveCSamplingLoggedAndExactNonmutating':True},'samplingDiagnosticsPolicy':{'sourcePolicy':'fixed-origin-stored-F32-X-and-raw-knots/v1','descriptiveOnly':True,'objectReferenceAndFieldsUnchangedAroundCopyExportAndCapture':True,'cameraIdentityHistoryAdvancingPolicyChanged':False,'notShaderCurtainOrVerticalWallAcceptance':True},'schemaAdaptation':{'experimentReadiness':'bounded-C-stable-X-native-readiness/v1','rootBuild':'bounded-C-stable-X-root-complete-build/v1','rootSeal':'bounded-C-stable-X-root-seal/v1','nativeReport':'bounded-C-stable-X-native-moving-shape/v1','finiteOwner':'bounded-C-stable-X-finite-owner/v1','inheritedSidecarCarrierAndCompatibleCPUFixtureSchemasKeepTheirExistingSemantics':True},'oldFailuresBytePinnedNotRetroaccepted':True,'newSourceNativeLeaseAndSamplingEvidencePending':True})
save('readiness.json',ready)
for q in helpers:verify(q)
print(json.dumps({'complete':True,'readiness':pin(W/'readiness.json'),'helperPins':pin(W/'helper-pins.json'),'helperCount':len(helpers),'sourcePins':len(build['sourcePins']),'assets':len(build['assetPins']),'resourcesStarted':False,'portsProbed':False,'rootSealNotCreated':True}))
