// Generated by `npm run barrels` — do not edit.
import type { BarrelCaseEntry } from './barrelLibrary';

export const BARREL_CASES: readonly BarrelCaseEntry[] = [
  {
    "id": "pad19-a20-l12",
    "spot": "padang",
    "slope": 0.0526316,
    "nonlinearity": 0.2,
    "flatDepth": 0.1785714,
    "asset": "barrels/pad19-a20-l12.bin"
  },
  {
    "id": "pad19-a30-l12",
    "spot": "padang",
    "slope": 0.0526316,
    "nonlinearity": 0.3,
    "flatDepth": 0.1785714,
    "asset": "barrels/pad19-a30-l12.bin"
  },
  {
    "id": "pad19-a45-l12",
    "spot": "padang",
    "slope": 0.0526316,
    "nonlinearity": 0.45,
    "flatDepth": 0.1785714,
    "asset": "barrels/pad19-a45-l12.bin"
  },
  {
    "id": "periodic-padang19s-l12",
    "spot": "padang",
    "slope": 0.0526316,
    "nonlinearity": 0.1414,
    "flatDepth": 0.1785714,
    "asset": "barrels/periodic-padang19s-l12.bin"
  },
  {
    "id": "periodic-reef42-l12",
    "spot": "reef",
    "slope": 0.238095,
    "nonlinearity": 0.2127,
    "flatDepth": 0.15,
    "asset": "barrels/periodic-reef42-l12.bin"
  },
  {
    "id": "periodic-point21-a15-l12",
    "spot": "point",
    "slope": 0.0465116,
    "nonlinearity": 0.1498,
    "flatDepth": 0.05,
    "asset": "barrels/periodic-point21-a15-l12.bin"
  },
  {
    "id": "periodic-point21-a23-l12",
    "spot": "point",
    "slope": 0.0465116,
    "nonlinearity": 0.2304,
    "flatDepth": 0.05,
    "asset": "barrels/periodic-point21-a23-l12.bin"
  },
  {
    "id": "periodic-point21-a30-l12",
    "spot": "point",
    "slope": 0.0465116,
    "nonlinearity": 0.2999,
    "flatDepth": 0.05,
    "asset": "barrels/periodic-point21-a30-l12.bin"
  }
];
