// Generated by `npm run barrels` — do not edit.
import type { BarrelCaseEntry } from './barrelLibrary';

export const BARREL_CASES: readonly BarrelCaseEntry[] = [
  {
    "id": "pad19-a20-l12",
    "slope": 0.0526316,
    "nonlinearity": 0.2,
    "flatDepth": 0.1785714,
    "asset": "barrels/pad19-a20-l12.bin"
  },
  {
    "id": "pad19-a30-l12",
    "slope": 0.0526316,
    "nonlinearity": 0.3,
    "flatDepth": 0.1785714,
    "asset": "barrels/pad19-a30-l12.bin"
  },
  {
    "id": "pad19-a45-l12",
    "slope": 0.0526316,
    "nonlinearity": 0.45,
    "flatDepth": 0.1785714,
    "asset": "barrels/pad19-a45-l12.bin"
  }
];
